### PR TITLE
Various timeline data panel and dragger pan related UI fixes

### LINKED ISSUE #2811: Day zoom level axis pan has wrong offset on update
**Describe the bug**
Day zoom level axis pan has wrong offset on update. In day zoom level. using pan by clicking near leading future edge doesn't update position offset correctly.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

### LINKED ISSUE #2815: Blue line inconsistent bottom alignment with luxor
**Describe the bug**
Blue line that shoots out of top of luxor isn't consistently aligned and is off a few pixels dependent on how many layers are visible in the data panel - three layers are in the data panel for below screenshot. Also, check top alignment where blue line meets date tooltip as well.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

### LINKED ISSUE #2829: Animation dragger is below data-bar chevron container
**Suggestion**
Adjust `z-index` so that animation dragger is above data-bar chevron container

Current ⬇️ 
Screen Shot 2020-04-10 at 1 42 33 PM

### PR DESCRIPTION
**Pull request by edplato**
## Description

Various timeline data panel and dragger pan related UI fixes.

- [x] Modify dragger pan axis update and extend rendered grids/modify leftbound. Fixes #2811 
- [x] Add to y axis blue line height. Fixes #2815 
- [x] Add leading `0` for date tooltip day of year < 10
- [x] Change `.data-panel-layer-item-date-range` position for consistent IE11 styling
- [x] Simplify data line position with boolean to improve weird background stripe rendering issue
- [x] Reorder `TimlineData` component to render behind animation draggers when unopened. Fixes #2829 

## Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

**Comment by jasontk19** [comment]
Not sure if this is addressed here but, this may be worth including in this work:  The panel tab is placed above the animation start/stop draggers which looks a little odd when they are lined up like this.
Screen Shot 2020-04-10 at 7 55 50 AM

**Comment by jasontk19** [comment]
These changes look good but this appears to introduce some choppiness into redrawing the timeline or availability bars when dragging past the edge of a bar. [See this video for a demo](https://drive.google.com/open?id=1nJUn1K9A_UbOrHI5NI4NTGhQTjxy4Yi6)

I'm not noticing this behavior on SIT.

**Comment by edplato** [comment]
I'm seeing that too if my dev console is open. I'll investigate what the bottleneck is.

**Comment by edplato** [comment]
After looking into this with Chrome, I didn't find a specific performance issue causing this choppy drag problem. The choppiness seems to be limited to `dev` builds while the devtools console is open. A `prod` build of this branch deployed to test UAT seems to drag smoothly with or without the devtools console open.

I think the core problem is inefficiencies in blocking updates within the parent `timeline.js` and outside with other repeatedly rendered components that needs to be addressed with a wider reaching fix/refactor.

**Pull request merged**
