### PR TITLE
WV-1932: Consistent date formatting

### PR DESCRIPTION
**Pull request by jasontk19**
## Description

Fixes WV-1932

Currently this PR includes changes from WV-1978 as well so that one should be reviewed/merged first.

- Remove unused layer measurement metadata files
- Update date formatting everywhere to follow `YYYY MMM DD HH:MM Z` format which is used by the timeline.

## How To Test

See ticket description for all the places to check date format

### CODE REVIEW

**Review by minniewong — COMMENTED** [review]
- The geostationary layers spell out the whole month name instead of MMM e.g. /?v=-138.89237333785655,-45.99016122596208,42.288222592375995,53.57233877403792&z=4&ics=true&ici=5&icd=10&l=Himawari_AHI_Band13_Clean_Infrared,GOES-West_ABI_Band2_Red_Visible_1km,GOES-West_ABI_GeoColor,CYGNSS_L3_Wind_Speed_SDR_Daily,Reference_Labels_15m(hidden),Reference_Features_15m(hidden),Coastlines_15m,MODIS_Terra_CorrectedReflectance_TrueColor&lg=true&t=2021-11-09-T17%3A54%3A01Z
- The summary box before going to Earthdata Search has the date as YYYY mmm DD. Should change to MMM.

**Review by Benjaki2 — CHANGES_REQUESTED** [review]
Code looks good to me.
I did notice two places where the global Format was not present:
* Within the GIF
* On hover of event track tool tips
Screen Shot 2021-11-17 at 11 03 34 AM

Screen Shot 2021-11-17 at 11 03 17 AM

I don't know if we want to make the GIF use this format or not 🤔

**Comment by jasontk19** [comment]
All comments should be addressed now.

**Review by minniewong — APPROVED** [review]
Looks good! I can't test the events anymore though after the domain change.

**Comment by jasontk19** [comment]
> Looks good! I can't test the events anymore though after the domain change.

Just pushed a rebase to develop to handle this as well

**Review by Benjaki2 — APPROVED** [review]
👍

**Pull request merged**
