### PR TITLE
Sedac vector layer release

### LINKED ISSUE #2144: Vector style enhancements for initial release
Style enhancements to vector products

**Sidebar**
- [x] bring legend out of setting dialog and into sidebar

**Map**
- [x] Show list of data instead of metadata for only top item clicked
- [x] if selected item in layer list is removed, remove selection
- [x] remove selected on proj change
~- [x] Hover interaction - add border or enlarge point~
- [x] Maybe add cursor change instead of actual map style change on hover
- [x] Emphasize selected point by adding a border 
- [x] add gradient to selected border
~wrap imagery~
- [x] Prevent click after map drag

**Dialog**
- [x] tabs for multi-layers, vertical
- [x] Make it so dialog doesn't reset location if already open. 
- [x] make it so you can click out of dialog
- [x] show valuemap value for relevant attributes
- [x] maybe format numbers
- [x] fix tooltip's hover flashing bug
- [x] change `bg` color to `white`
- [x] bigger modal (resize?)
- [x] start dialog in position that does not cover selected point
- [x] Make selected points stand out more
- [x] replace attribute title with intended title in json
- [x] possibly(Definitely) show units
- [x] ordering (either GIBS or in wv-config)
- [x] cell is th: replace with body cells
- [x] fix drag lag
- [x] set max number of tabs (or see if stacking works)
- [x] move `(i)` component to start of row
- [x] add simplebar scrolling
- [x] prevent uppercasing units
- [x] scrollbar not showing up in some cases

### LINKED ISSUE #2360: Add snapshots wms matching support for vector layers
**Is your feature request related to a problem? Please describe.**
At this point vector layers are not handled by worldview snapshots

**Describe the solution you'd like**
 snapshot requests should include the corresponding wms layer for vector layers at this point

**Describe alternatives you've considered**
Support vector layers in snapshots backend

**Additional context**
GIBS will continue to support WMS support for layers

### PR DESCRIPTION
**Pull request by Benjaki2**
## Description

Fixes #2144 
Fixes #2360 

- [x] Fix styling of vector dialog and selected features 
- [x] Configure vector layers for prod

## WMS layers replaced by Vector Layers
* Reservoirs
* Dams
* Nuclear power plants

## Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

**Comment by jasontk19** [comment]
- [ ]  Using the measure tool on this branch causes the following console error:
```
Uncaught TypeError: Cannot read property 'wv' of null
    at runningdata.js:72
    at forEachFeatureAtCoordinate (Map.js:132)
    at VectorLayer.js:250
...
```

- [ ]  I found an issue where clicking on multiple successive points (confirmed with settlements, reservoirs) show the metadata for the first selection only.  Probably easier to see what I mean here: https://drive.google.com/open?id=1UGQxWO-nRy5YhQ-NcWXgbzDuxBe8fKtk

- [ ]  Currently text within the metadata dialogs is not selectable.  It might be nice to allow selection and set the dialog header to the draggable target, with a "move" cursor.  This way users can easily highlight and copy text from the dialog if desired.

**Comment by Benjaki2** [comment]
Good finds @jasontk19 and thanks for the recommendations. Those features/fixes should be in now 🤞and the layers are on PROD so you should be able to build with this branch as well.

**Comment by jasontk19** [comment]
Changes look great!  For some reason though, I'm no longer getting mouse interactions for the settlements layer.  No console errors either. 🤷‍♂

**Comment by Benjaki2** [comment]
@jasontk19 Settlements isn't going out with this release. Just added the list of vector-layers to the description. It's just Damns, reservoirs, and Power plants. Running data should be working again, now!

**Pull request merged**
