### PR TITLE
WV-2622 invisible flags

### PR DESCRIPTION
**Pull request by Tomcariello**
## Description
There are imagery layers which contain transparent pixel values which could be rendered as opaque in Worldview. It would be good to allow users to toggle these pixel values on as needed. We would want these classifications off by default, but a user could toggle them on if wanted.

One example is the [MODIS sea ice product ](http://localhost:3000/?v=-315.0774629899484,-247.99306208393455,345.39659883674705,200.86311393833853&l=MODIS_Terra_L3_Sea_Ice_Daily(disabled=0-1-2-3-4-5-6-8-9-10),VIIRS_SNPP_CorrectedReflectance_TrueColor&lg=false&t=2023-05-01-T12%3A38%3A10Z)having embedded flags for quantities such as "no data due to cloud cover". Some users may want to know why there is no data available and this would allow them to see the reason.

Fixes # WV-2622.

## How To Test

- git checkout wv-2622-invisible-flags
- npm run build
- npm run watch
- View layer with hidden data in the served tiles (such as the sea ice layer above)
- click on 'View Options' for that layer
- Toggle colors on/off & confirm the visuals update as expected

@nasa-gibs/worldview

### CODE REVIEW

**Review by ryanweiler92 — CHANGES_REQUESTED** [review]
The image-download/unsupported-test.spec.js e2e test may need to be updated. It looks like it is failing due to some changes made to palette selections. Let me know if it seems like this is failing from something other than your changes.

**Review by ryanweiler92 — APPROVED** [review]
Awesome! I just wanted to double check since I saw you installed 2 new dependencies. I see the `upng-js` is being used, but I'm not seeing where `pako` is being used. I could just be totally missing it..

**Review by PatchesMaps — APPROVED** [review]

**Review by minniewong — CHANGES_REQUESTED** [review]
The OPERA DSWx (Surface Water Extent) layer is throwing an error, and the black "no data" should be off by default.
 __webpack_modules__../web/js/ol/lookupimagetile.js.LookupImageTile.load
  wv.js?v=@BUILD_NONCE@:77206:7
 TileQueue.loadMoreTiles
  wv.js?v=@BUILD_NONCE@:266397:14
 Map.handlePostRender
  wv.js?v=@BUILD_NONCE@:263355:19
 undefined
  wv.js?v=@BUILD_NONCE@:263786:14

**Comment by minniewong** [comment]
[Sea Ice Brightness Temperature](http://localhost:3000/?l=Reference_Labels_15m(hidden),Reference_Features_15m(hidden),Coastlines_15m,AMSRU2_Sea_Ice_Brightness_Temp_6km_89H,VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor&lg=true&t=2023-06-27-T18%3A59%3A32Z) throws the following error even though it's not a classified layer
TypeError
Cannot read properties of undefined (reading 'maps')
Call Stack
 undefined
  wv.js?v=@BUILD_NONCE@:70778:35
 undefined
  wv.js?v=@BUILD_NONCE@:209543:18
 toggleAllClassifications
  wv.js?v=@BUILD_NONCE@:25822:5
 PaletteLegend.componentDidMount
  wv.js?v=@BUILD_NONCE@:25412:9
 commitLifeCycles
  wv.js?v=@BUILD_NONCE@:185363:24
 commitLayoutEffects
  wv.js?v=@BUILD_NONCE@:188126:7
 HTMLUnknownElement.callCallback
  wv.js?v=@BUILD_NONCE@:168650:14
 Object.invokeGuardedCallbackDev
  wv.js?v=@BUILD_NONCE@:168699:16
 invokeGuardedCallback
  wv.js?v=@BUILD_NONCE@:168761:31
 commitRootImpl
  wv.js?v=@BUILD_NONCE@:187851:9

**Comment by minniewong** [comment]
When you load the Assessing Floodwaters tour story, the first step correctly has the "No Data" and "No Water" values off. When you go to the second step of the story, the values are now on and persistently stay on. It appears the URL parameters for hiding classifications is now not properly aligned with the correct values.

**Comment by Tomcariello** [comment]
Fixed in the latest commit. Thanks.

**Comment by Tomcariello** [comment]
Fixed in the latest commit. Thanks.

**Comment by Tomcariello** [comment]
> When you load the Assessing Floodwaters tour story, the first step correctly has the "No Data" and "No Water" values off. When you go to the second step of the story, the values are now on and persistently stay on. It appears the URL parameters for hiding classifications is now not properly aligned with the correct values.

Because we have changed the number (and order) of palette items we will need to update each of these step links (in each of the tour stories) to re-align the URL parameters. 

However, any URLs made/shared prior to this feature will potentially load palettes differently than expected.

**Comment by Tomcariello** [comment]
The Flood Tour (and the Swath Tour) are fixed in the latest commit.

**Comment by Tomcariello** [comment]
> 

This one was a bit weird. It's addressed in the latest commit but may be worth a closer look. The [GC for this layer](https://gibs.earthdata.nasa.gov/colormaps/v1.3/OPERA_Dynamic_Surface_Water_Extent.xml) begins with a ref of 255. For comparison, [Sea Ice L3](https://gibs.earthdata.nasa.gov/colormaps/v1.3/MODIS_L3_Sea_Ice.xml) has the ref start at 0 & increase incrementally which appears to be the standard based on what I have seen.

**Comment by Tomcariello** [comment]
> > 
> 
> This one was a bit weird. It's addressed in the latest commit but may be worth a closer look. The [GC for this layer](https://gibs.earthdata.nasa.gov/colormaps/v1.3/OPERA_Dynamic_Surface_Water_Extent.xml) begins with a ref of 255. For comparison, [Sea Ice L3](https://gibs.earthdata.nasa.gov/colormaps/v1.3/MODIS_L3_Sea_Ice.xml) has the ref start at 0 & increase incrementally which appears to be the standard based on what I have seen.



> The [OPERA DSWx (Surface Water Extent) layer](http://localhost:3000/?l=Reference_Labels_15m(hidden),Reference_Features_15m(hidden),Coastlines_15m,OPERA_L3_Dynamic_Surface_Water_Extent-HLS_Provisional(disabled=255),VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor&lg=true&t=2023-06-27-T19%3A30%3A43Z) is throwing an error, and the black "no data" should be off by default.
> 
> TypeError Failed to fetch Call Stack  **webpack_modules**../web/js/ol/lookupimagetile.js.LookupImageTile.load   wv.js?v=@BUILD_NONCE@:77206:7  TileQueue.loadMoreTiles   wv.js?v=@BUILD_NONCE@:266397:14  Map.handlePostRender   wv.js?v=@BUILD_NONCE@:263355:19  undefined   wv.js?v=@BUILD_NONCE@:263786:14

**Comment by Tomcariello** [comment]
> The [OPERA DSWx (Surface Water Extent) layer](http://localhost:3000/?l=Reference_Labels_15m(hidden),Reference_Features_15m(hidden),Coastlines_15m,OPERA_L3_Dynamic_Surface_Water_Extent-HLS_Provisional(disabled=255),VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor&lg=true&t=2023-06-27-T19%3A30%3A43Z) is throwing an error, and the black "no data" should be off by default.
> 
> TypeError Failed to fetch Call Stack  **webpack_modules**../web/js/ol/lookupimagetile.js.LookupImageTile.load   wv.js?v=@BUILD_NONCE@:77206:7  TileQueue.loadMoreTiles   wv.js?v=@BUILD_NONCE@:266397:14  Map.handlePostRender   wv.js?v=@BUILD_NONCE@:263355:19  undefined   wv.js?v=@BUILD_NONCE@:263786:14

This is fixed in the latest commit. Thanks.

**Comment by minniewong** [comment]
When I try to add "Sea Ice Concentration (12km)" AMSRU2_Sea_Ice_Concentration_12km, I get an error message. Not sure why since this one doesn't even have invisible flags.

Screenshot 2023-07-13 at 4 40 42 PM

**Comment by Tomcariello** [comment]
> When I try to add "Sea Ice Concentration (12km)" AMSRU2_Sea_Ice_Concentration_12km, I get an error message. Not sure why since this one doesn't even have invisible flags. Steps to recreate:
> 
> * Go to Add Layers
> * Type in Sea Ice
> * Select Sea ice Concentration (12 km) (which is 8th on the list)
> * See error
> 
> Screenshot 2023-07-13 at 4 40 42 PM

I cannot replicate this error, the Sea Ice Concentraion (12 km) layer loads properly here on windows & Mac. Can you please pull latest, re-build & retry? Thanks!

**Comment by minniewong** [comment]
@Tomcariello ok the Sea Ice works now haha

**Comment by Tomcariello** [comment]
> I tried again, and the error seems to pop up when I first add the regular Sea Ice (MODIS/Terra) or Aqua layer, then the Sea Ice Concentration (12km) AMSR2. Steps to recreate:
> 
> 1. Search for "Sea Ice" in the Layer Picker
> 2. Add Sea Ice (MODIS/Terra)
> 3. Add Sea Ice Concentration (GCOM-W1/AMSR2)
> 4. See above error

Thanks for this. Fixed in the latest commit.

**Pull request merged**
