### PR TITLE
Remove extra dragger container width

### PR DESCRIPTION
**Pull request by edplato**
## Description

Related to fix #2643 

- [x] Remove extra dragger container width
- [x]  Revise mobile dragger left and bottom style positioning based on screen width and subdaily layers

## Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

**Comment by jasontk19** [comment]
Screen Shot 2020-02-14 at 3 54 49 PM

This looks fine at desktop size though, in a somewhat related matter, the left/right arrows now overlap the datepicker button on mobile due to a couple of recent PRs that recently went in separately but do not play nicely together 😬 We can either open a separate ticket for that or we can just add it on here.  Up to you!

I'm happy to open a new ticket and assign to me since I messed with the mobile datepicker sizing originally.

**Comment by edplato** [comment]
Ok, I missed that overlapping, but definitely see it now. Looks like there is another other issue with the longer subdaily mobile time text too that may require stacking the left/right arrows on top of the text. We should tighten up both issues for this release.

image

I can try to tack the fixes on the PR instead of a new ticket.

**Comment by edplato** [comment]
I see potential areas of improvement, but I feel these dynamic styling changes are a good start to get this feature out.

**Normal mobile view (no subdaily):**
image

**Subdaily moves arrows up and to the left:**
image

**Comment by jasontk19** [comment]
Looks good! Only thing I'd add is that it might look a little cleaner if the arrows are roughly the same height as the datepicker and measure tool button:
Screen Shot 2020-02-18 at 12 53 41 PM

**Comment by edplato** [comment]
Sound good, made a couple changes to even everything out:
image

**Comment by jasontk19** [comment]
Nice! I like how it stays inline with the datepicker until it would come too close and start to overlap.  :shipit:

**Pull request merged**
