### PR TITLE
WV-3045 WVS granule layer snapshots

### PR DESCRIPTION
**Pull request by PatchesMaps**
## Description

> Update WV to pass WVS required data for granule snapshots

## How To Test

1. `git checkout WV-3045-wvs-granule`
2. `npm run watch`
3. Open this [link](http://localhost:3000/?v=-194.83679430000677,-65.4807177676953,51.93454726415837,76.32711913810098&ics=true&ici=5&icd=10&l=VIIRS_NOAA20_CorrectedReflectance_BandsM3-I3-M11_Granule(hidden,count=10),VIIRS_NOAA20_CorrectedReflectance_BandsM11-I2-I1_Granule(hidden,count=10),VIIRS_NOAA20_CorrectedReflectance_TrueColor_Granule(count=10),VIIRS_SNPP_CorrectedReflectance_BandsM3-I3-M11_Granule(hidden,count=10),VIIRS_SNPP_CorrectedReflectance_BandsM11-I2-I1_Granule(hidden,count=10),VIIRS_SNPP_CorrectedReflectance_TrueColor_Granule(hidden,count=10),Land_Water_Map&lg=true&t=2024-04-18-T21%3A10%3A00Z)
4. Create snapshots with different granule layers and make sure they come back correct.

## PR Submission Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/main/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

## Merging

Please use the `squash and merge` commit method unless each commit in your branch is vital to the commit history of main.

@nasa-gibs/worldview

### CODE REVIEW

**Review by ryanweiler92 — COMMENTED** [review]
Everything looks good here but I realized that I needed to make a change on the backend to be able to handle when a snapshot is taken that crosses the dateline with granules. EX: https://wvs.earthdata.nasa.gov/api/v1/snapshot?REQUEST=GetSnapshot&TIME=2024-05-02T12:12:00Z&BBOX=13.6418,128.3159,63.9881,189.3273&CRS=EPSG:4326&LAYERS=MODIS_Terra_CorrectedReflectance_TrueColor,Coastlines_15m,VIIRS_SNPP_CorrectedReflectance_BandsM11-I2-I1_Granule&WRAP=day,x,none&FORMAT=image/jpeg&WIDTH=1388&HEIGHT=1146&granule_dates=2;2024-05-02T00:36,2024-05-02T01:48,2024-05-02T01:54,2024-05-02T02:00,2024-05-02T02:06,2024-05-02T02:12,2024-05-02T03:30,2024-05-02T03:36,2024-05-02T03:42,2024-05-02T03:48,&ts=1714656193239

I made a PR for this on the backend but we may want to wait to merge this until that is in PROD.

**Comment by Tomcariello** [comment]
Every snapshot that I take does not contain the granules. Am I doing something wrong?

I did run `npm run build` prior to testing.

**Comment by PatchesMaps** [comment]
We're limiting the number of granules that get sent to WVS to 15 so it's possible that they're getting truncated. Have you tried with only one layer?

**Comment by Tomcariello** [comment]
The request works on the latest WVS (running locally) but no granules show up in Production WVS. 

The link Ryan provided returns black from Prod but works in latest WVS, too. 

Is that expected?

**Review by minniewong — APPROVED** [review]

**Review by christof-wittreich — APPROVED** [review]

**Pull request merged**
