### PR TITLE
Add WDPA Layer

### LINKED ISSUE #220: Date line should be always visible in mobile
The date line on the left and right of the current day's imagery is not viewable in mobile at the moment. This feature should be enabled so that it looks like the desktop version.

### LINKED ISSUE #603: Add World Database on Protected Areas layer
Add the World Database on Protected Areas (WDPA) layer via the World Conservation Monitoring Centre (WCMC) WMS:

http://gis.unep-wcmc.org:6080/arcgis/services/wdpa/public/MapServer/WMSServer?request=GetCapabilities&service=WMS

The info box should link to the data set terms and conditions:
http://www.protectedplanet.net/terms

and to the download of the data set at:
www.protectedplanet.net

### PR DESCRIPTION
**Pull request by mike-mcgann**
## Description

Fixes #603.

- Add WDPA Layer

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- [x] I have added necessary documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] Any dependent changes have been merged and published in downstream modules (if applicable)

## Further comments

If this is a relatively large or complex change, start a discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

@nasa-gibs/worldview

### CODE REVIEW

**Comment by mike-mcgann** [comment]
WVS-165 is separate.

**Comment by minniewong** [comment]
Could you also have the layer wrap?

**Comment by mike-mcgann** [comment]
Added the wrap. Take a look again. 

Correct on WVS-165.

**Comment by minniewong** [comment]
Should it be "wrapX" instead of "wrapadjacentdays"?

**Comment by mike-mcgann** [comment]
Yes

**Comment by mike-mcgann** [comment]
Check now

**Comment by minniewong** [comment]
looks good- thanks!

**Pull request merged**
