### PR TITLE
Playwright Integration

### PR DESCRIPTION
**Pull request by ryanweiler92**
## Description 

This PR converts our end to end testing from Nightwatch.js/Selenium to Playwright. 

- Converted 50+ e2e tests from Nightwatch.js to Playwright
- Removed all Nighwatch.js & Selenium dependencies 
- Updated Docker files to incorporate Playwright testing
- Updated `testing.md` doc
- Incorporated Playwright into GitHub actions

## How to test

1. `git checkout playwright-integration`
2. `npm ci`
3. `npm run build`
4. `npm run watch`
5. `npm run e2e:headless`
6. Ensure that all of the tests run & pass. Please let me know if there are any failures and which ones have failed & on which browser. This should only take about 10 minutes.

### CODE REVIEW

**Comment by Tomcariello** [comment]
I had 2 tests fail, both Webkit.

**Clicking the animation widget button opens the widget**
Error: expect(received).toHaveText(expected)
Expected string: "0"
Received string: "-18"

**Clicking Shorten link is refused with links greater than 2048 characters**
Test timeout of 30000ms exceeded.

**Comment by victorsh** [comment]
Getting one error with webkit
```
Running 924 tests using 8 workers
  1) [webkit] › events/events-mobile-test.spec.js:25:1 › Events populated in sidebar ===============

    Error: expect(received).toBeVisible()
    Call log:
      - expect.toBeVisible with timeout 5000ms
      - waiting for locator('#wv-events #sidebar-event-EONET_2703')
      -   unexpected value "hidden"
      - waiting for locator('#wv-events #sidebar-event-EONET_2703')
      -   unexpected value "hidden"
      -   unexpected value "hidden"
      -   unexpected value "hidden"
      -   unexpected value "hidden"
      -   unexpected value "hidden"
      -   unexpected value "hidden"
      -   unexpected value "hidden"
      -   unexpected value "hidden"


      32 |   await eventsTab.click()
      33 |   await page.waitForTimeout(1500)
    > 34 |   await expect(icebergEvent).toBeVisible()
         |                              ^
      35 | })
      36 |
      37 | test('Clicking event in list closes sidebar and selects marker for event on map', async ({ browserName }) => {

        at /Users/vsh/Documents/github/nasa/worldview/e2e/features/events/events-mobile-test.spec.js:34:30


  1 failed
    [webkit] › events/events-mobile-test.spec.js:25:1 › Events populated in sidebar ================
  20 skipped
  903 passed (6.1m)
 ```

**Review by minniewong — COMMENTED** [review]
Seems like I had a lot fail 
` 151 failed
    [chromium] › animation/animation-test.spec.js:20:1 › Clicking the animation widget button opens the widget 
    [chromium] › animation/gif-test.spec.js:25:1 › Clicking the animation widget button opens the widget 
    [chromium] › animation/mobile-animation-test.spec.js:22:1 › Clicking the animation widget button opens the widget 
    [chromium] › compare/compare-mobile-test.spec.js:22:1 › Mobile comparison A|B toggle buttons are visible and only A is selected by default 
    [chromium] › compare/compare-test.spec.js:20:1 › Animation is disabled when compare mode active 
    [chromium] › compare/layer-dialog-test.spec.js:30:1 › Layer option features work in A|B mode ===
    [chromium] › compare/layer-sidebar-test.spec.js:24:1 › Add AOD Layer to Layer Group A ==========
    [chromium] › compare/permalinks-test.spec.js:24:1 › Swipe mode and A|B state A are active and date is correct 
    [chromium] › compare/timeline-test.spec.js:21:1 › Verify that A|B draggers are visible =========
    [chromium] › events/event-filter-test.spec.js:40:1 › Default filtering includes last 120 days and all categories 
    [chromium] › events/event-test.spec.js:20:1 › Make sure that 4 fire layers are not present in layer list: use mock 
    [chromium] › events/events-mobile-test.spec.js:25:1 › Events populated in sidebar ==============
    [chromium] › global-unit/coordinate-format-test.spec.js:21:1 › Open page =======================
    [chromium] › global-unit/global-unit-test.spec.js:28:1 › Global settings menu item opens global settings modal 
    [chromium] › image-download/crosses-dateline-test.spec.js:20:1 › No dateline alert notification with message if not crossing dateline(s) 
    [chromium] › image-download/formats-test.spec.js:34:1 › JPEG is the default ====================
    [chromium] › image-download/global-select-test.spec.js:32:1 › Verify that global select is present and not selected 
    [chromium] › image-download/initial-state-test.spec.js:31:1 › Check resolutions ================
    [chromium] › image-download/lat-long-input-test.spec.js:31:1 › Check that image download inputs are hidden on initial load 
    [chromium] › image-download/layers-test.spec.js:24:1 › List layers in draw order ===============
    [chromium] › image-download/projection-test.spec.js:28:1 › Geographic is EPSG:4326 =============
    [chromium] › image-download/resolutions3413-test.spec.js:34:1 › In the arctic, top zoom levels is 5km 
    [chromium] › image-download/resolutions4326-test.spec.js:34:1 › In geographic, top two zoom levels are 10km 
    [chromium] › image-download/time-test.spec.js:26:1 › Image for today ===========================
    [chromium] › image-download/unsupported-test.spec.js:31:1 › Custom palettes are not supported dialog 
    [chromium] › layers/layer-picker-mobile-test.spec.js:25:1 › Initial state indicates layer count 
    [chromium] › layers/layer-picker-test.spec.js:22:1 › Layer picker shows categories when first opened 
    [chromium] › layers/layers-sidebar-test.spec.js:48:1 › Toggle layer Info =======================
    [chromium] › layers/layers-vector-test.spec.js:22:1 › Vector layer click does not show alert when all vector layers are clickable 
    [chromium] › layers/options-test.spec.js:21:1 › Verify that settings button opens settings modal 
    [chromium] › layers/recent-layers-mobile-test.spec.js:25:1 › Layer picker shows categories when first opened 
    [chromium] › layers/recent-layers-no-local-storage-test.spec.js:22:1 › Verify that recent layers tab does not show when local storage is disabled 
    [chromium] › layers/recent-layers-test.spec.js:22:1 › Layer picker shows categories when first opened 
    [chromium] › location-search/location-search-mobile-test.spec.js:23:1 › Location Search component is visible by default 
    [chromium] › location-search/location-search-test.spec.js:24:1 › Location Search component is visible by default 
    [chromium] › measure/measure-test.spec.js:29:1 › Clicking the measure button opens the menu ====
    [chromium] › modal/about-modal-test.spec.js:24:1 › About modal not open when URL param not present 
    [chromium] › notifications/notify-test.spec.js:31:1 › No visible notifications with mockAlert parameter set to no_types 
    [chromium] › palettes/disable-test.spec.js:18:1 › Verify that toggling class updates permalink and layer-legend 
    [chromium] › projections/projections-test.spec.js:21:1 › Verify default page shows projection toolbar button in geographic projection map 
    [chromium] › share/share-test.spec.js:23:1 › Clicking the share link button opens the share dialog 
    [chromium] › smart-handoff/smart-handoff-test.spec.js:19:1 › Data tab is available and in default state when clicked 
    [chromium] › timeline/date-selector-test.spec.js:20:1 › Verify subdaily default year, month, day, hour, minute date selector inputs 
    [chromium] › timeline/layer-coverage-panel-test.spec.js:17:1 › Layer coverage is shown by default 
    [chromium] › timeline/timeline-mobile-test.spec.js:22:1 › date.mob.init.2a: Before 3:00 UTC: load yesterdays date 
    [chromium] › timeline/timeline-test.spec.js:24:1 › Dragger is visible ==========================
    [chromium] › tour/tour-test.spec.js:20:1 › Verify that all tour modals are present when the page is loaded 
    [chromium] › ui/distraction-free-mode-test.spec.js:73:1 › Enabling distraction free mode with shortcut key hides UI elements 
    [chromium] › ui/info-mobile-test.spec.js:23:1 › Mobile info toolbar is visible and contains valid mobile menu items 
    [chromium] › ui/info-test.spec.js:20:1 › Info toolbar is visible and contains valid menu items =
    [chromium] › ui/toolbar-test.spec.js:20:1 › Info toolbar is visible and contains valid menu items 
    [firefox] › animation/animation-test.spec.js:20:1 › Clicking the animation widget button opens the widget 
    [firefox] › animation/gif-test.spec.js:25:1 › Clicking the animation widget button opens the widget 
    [firefox] › animation/mobile-animation-test.spec.js:22:1 › Clicking the animation widget button opens the widget 
    [firefox] › compare/compare-mobile-test.spec.js:22:1 › Mobile comparison A|B toggle buttons are visible and only A is selected by default 
    [firefox] › compare/compare-test.spec.js:20:1 › Animation is disabled when compare mode active =
    [firefox] › compare/layer-dialog-test.spec.js:30:1 › Layer option features work in A|B mode ====
    [firefox] › compare/layer-sidebar-test.spec.js:24:1 › Add AOD Layer to Layer Group A ===========
    [firefox] › compare/permalinks-test.spec.js:24:1 › Swipe mode and A|B state A are active and date is correct 
    [firefox] › compare/timeline-test.spec.js:21:1 › Verify that A|B draggers are visible ==========
    [firefox] › events/event-filter-test.spec.js:40:1 › Default filtering includes last 120 days and all categories 
    [firefox] › global-unit/coordinate-format-test.spec.js:21:1 › Open page ========================
    [firefox] › global-unit/global-unit-test.spec.js:28:1 › Global settings menu item opens global settings modal 
    [firefox] › image-download/crosses-dateline-test.spec.js:20:1 › No dateline alert notification with message if not crossing dateline(s) 
    [firefox] › image-download/formats-test.spec.js:34:1 › JPEG is the default =====================
    [firefox] › image-download/global-select-test.spec.js:32:1 › Verify that global select is present and not selected 
    [firefox] › image-download/initial-state-test.spec.js:31:1 › Check resolutions =================
    [firefox] › image-download/lat-long-input-test.spec.js:31:1 › Check that image download inputs are hidden on initial load 
    [firefox] › image-download/layers-test.spec.js:24:1 › List layers in draw order ================
    [firefox] › image-download/projection-test.spec.js:28:1 › Geographic is EPSG:4326 ==============
    [firefox] › image-download/resolutions3413-test.spec.js:34:1 › In the arctic, top zoom levels is 5km 
    [firefox] › image-download/resolutions4326-test.spec.js:34:1 › In geographic, top two zoom levels are 10km 
    [firefox] › image-download/time-test.spec.js:26:1 › Image for today ============================
    [firefox] › image-download/unsupported-test.spec.js:31:1 › Custom palettes are not supported dialog 
    [firefox] › layers/layer-picker-mobile-test.spec.js:25:1 › Initial state indicates layer count =
    [firefox] › layers/layer-picker-test.spec.js:22:1 › Layer picker shows categories when first opened 
    [firefox] › layers/layers-sidebar-test.spec.js:48:1 › Toggle layer Info ========================
    [firefox] › layers/layers-vector-test.spec.js:22:1 › Vector layer click does not show alert when all vector layers are clickable 
    [firefox] › layers/options-test.spec.js:21:1 › Verify that settings button opens settings modal 
    [firefox] › layers/recent-layers-mobile-test.spec.js:25:1 › Layer picker shows categories when first opened 
    [firefox] › layers/recent-layers-no-local-storage-test.spec.js:22:1 › Verify that recent layers tab does not show when local storage is disabled 
    [firefox] › layers/recent-layers-test.spec.js:22:1 › Layer picker shows categories when first opened 
    [firefox] › location-search/location-search-mobile-test.spec.js:23:1 › Location Search component is visible by default 
    [firefox] › location-search/location-search-test.spec.js:24:1 › Location Search component is visible by default 
    [firefox] › measure/measure-test.spec.js:29:1 › Clicking the measure button opens the menu =====
    [firefox] › modal/about-modal-test.spec.js:24:1 › About modal not open when URL param not present 
    [firefox] › notifications/notify-test.spec.js:31:1 › No visible notifications with mockAlert parameter set to no_types 
    [firefox] › palettes/disable-test.spec.js:18:1 › Verify that toggling class updates permalink and layer-legend 
    [firefox] › projections/projections-test.spec.js:21:1 › Verify default page shows projection toolbar button in geographic projection map 
    [firefox] › share/share-test.spec.js:23:1 › Clicking the share link button opens the share dialog 
    [firefox] › smart-handoff/smart-handoff-test.spec.js:19:1 › Data tab is available and in default state when clicked 
    [firefox] › timeline/date-selector-test.spec.js:20:1 › Verify subdaily default year, month, day, hour, minute date selector inputs 
    [firefox] › timeline/layer-coverage-panel-test.spec.js:17:1 › Layer coverage is shown by default 
    [firefox] › timeline/timeline-mobile-test.spec.js:22:1 › date.mob.init.2a: Before 3:00 UTC: load yesterdays date 
    [firefox] › timeline/timeline-test.spec.js:24:1 › Dragger is visible ===========================
    [firefox] › tour/tour-test.spec.js:20:1 › Verify that all tour modals are present when the page is loaded 
    [firefox] › ui/distraction-free-mode-test.spec.js:73:1 › Enabling distraction free mode with shortcut key hides UI elements 
    [firefox] › ui/info-mobile-test.spec.js:23:1 › Mobile info toolbar is visible and contains valid mobile menu items 
    [firefox] › ui/info-test.spec.js:20:1 › Info toolbar is visible and contains valid menu items ==
    [firefox] › ui/toolbar-test.spec.js:20:1 › Info toolbar is visible and contains valid menu items 
    [webkit] › animation/animation-test.spec.js:20:1 › Clicking the animation widget button opens the widget 
    [webkit] › animation/gif-test.spec.js:25:1 › Clicking the animation widget button opens the widget 
    [webkit] › animation/mobile-animation-test.spec.js:22:1 › Clicking the animation widget button opens the widget 
    [webkit] › compare/compare-mobile-test.spec.js:22:1 › Mobile comparison A|B toggle buttons are visible and only A is selected by default 
    [webkit] › compare/compare-test.spec.js:20:1 › Animation is disabled when compare mode active ==
    [webkit] › compare/layer-dialog-test.spec.js:30:1 › Layer option features work in A|B mode =====
    [webkit] › compare/layer-sidebar-test.spec.js:24:1 › Add AOD Layer to Layer Group A ============
    [webkit] › compare/permalinks-test.spec.js:24:1 › Swipe mode and A|B state A are active and date is correct 
    [webkit] › compare/timeline-test.spec.js:21:1 › Verify that A|B draggers are visible ===========
    [webkit] › events/event-filter-test.spec.js:40:1 › Default filtering includes last 120 days and all categories 
    [webkit] › events/event-test.spec.js:20:1 › Make sure that 4 fire layers are not present in layer list: use mock 
    [webkit] › events/events-mobile-test.spec.js:25:1 › Events populated in sidebar ================
    [webkit] › global-unit/coordinate-format-test.spec.js:21:1 › Open page =========================
    [webkit] › global-unit/global-unit-test.spec.js:28:1 › Global settings menu item opens global settings modal 
    [webkit] › image-download/crosses-dateline-test.spec.js:20:1 › No dateline alert notification with message if not crossing dateline(s) 
    [webkit] › image-download/formats-test.spec.js:34:1 › JPEG is the default ======================
    [webkit] › image-download/global-select-test.spec.js:32:1 › Verify that global select is present and not selected 
    [webkit] › image-download/initial-state-test.spec.js:31:1 › Check resolutions ==================
    [webkit] › image-download/lat-long-input-test.spec.js:31:1 › Check that image download inputs are hidden on initial load 
    [webkit] › image-download/layers-test.spec.js:24:1 › List layers in draw order =================
    [webkit] › image-download/projection-test.spec.js:28:1 › Geographic is EPSG:4326 ===============
    [webkit] › image-download/resolutions3413-test.spec.js:34:1 › In the arctic, top zoom levels is 5km 
    [webkit] › image-download/resolutions4326-test.spec.js:34:1 › In geographic, top two zoom levels are 10km 
    [webkit] › image-download/time-test.spec.js:26:1 › Image for today =============================
    [webkit] › image-download/unsupported-test.spec.js:31:1 › Custom palettes are not supported dialog 
    [webkit] › layers/layer-picker-mobile-test.spec.js:25:1 › Initial state indicates layer count ==
    [webkit] › layers/layer-picker-test.spec.js:22:1 › Layer picker shows categories when first opened 
    [webkit] › layers/layers-sidebar-test.spec.js:48:1 › Toggle layer Info =========================
    [webkit] › layers/layers-vector-test.spec.js:22:1 › Vector layer click does not show alert when all vector layers are clickable 
    [webkit] › layers/options-test.spec.js:21:1 › Verify that settings button opens settings modal =
    [webkit] › layers/recent-layers-mobile-test.spec.js:25:1 › Layer picker shows categories when first opened 
    [webkit] › layers/recent-layers-no-local-storage-test.spec.js:22:1 › Verify that recent layers tab does not show when local storage is disabled 
    [webkit] › layers/recent-layers-test.spec.js:22:1 › Layer picker shows categories when first opened 
    [webkit] › location-search/location-search-mobile-test.spec.js:23:1 › Location Search component is visible by default 
    [webkit] › location-search/location-search-test.spec.js:24:1 › Location Search component is visible by default 
    [webkit] › measure/measure-test.spec.js:29:1 › Clicking the measure button opens the menu ======
    [webkit] › modal/about-modal-test.spec.js:24:1 › About modal not open when URL param not present 
    [webkit] › notifications/notify-test.spec.js:31:1 › No visible notifications with mockAlert parameter set to no_types 
    [webkit] › palettes/disable-test.spec.js:18:1 › Verify that toggling class updates permalink and layer-legend 
    [webkit] › projections/projections-test.spec.js:21:1 › Verify default page shows projection toolbar button in geographic projection map 
    [webkit] › share/share-test.spec.js:23:1 › Clicking the share link button opens the share dialog 
    [webkit] › smart-handoff/smart-handoff-test.spec.js:19:1 › Data tab is available and in default state when clicked 
    [webkit] › timeline/date-selector-test.spec.js:20:1 › Verify subdaily default year, month, day, hour, minute date selector inputs 
    [webkit] › timeline/layer-coverage-panel-test.spec.js:17:1 › Layer coverage is shown by default 
    [webkit] › timeline/timeline-mobile-test.spec.js:22:1 › date.mob.init.2a: Before 3:00 UTC: load yesterdays date 
    [webkit] › timeline/timeline-test.spec.js:24:1 › Dragger is visible ============================
    [webkit] › tour/tour-test.spec.js:20:1 › Verify that all tour modals are present when the page is loaded 
    [webkit] › ui/distraction-free-mode-test.spec.js:73:1 › Enabling distraction free mode with shortcut key hides UI elements 
    [webkit] › ui/info-mobile-test.spec.js:23:1 › Mobile info toolbar is visible and contains valid mobile menu items 
    [webkit] › ui/info-test.spec.js:20:1 › Info toolbar is visible and contains valid menu items ===
    [webkit] › ui/toolbar-test.spec.js:20:1 › Info toolbar is visible and contains valid menu items 
  773 skipped`

**Comment by ryanweiler92** [comment]
> Seems like I had a lot fail!
> 
> 151 failed [chromium] › animation/animation-test.spec.js:20:1 › Clicking the animation widget button opens the widget [chromium] › animation/gif-test.spec.js:25:1 › Clicking the animation widget button opens the widget [chromium] › animation/mobile-animation-test.spec.js:22:1 › Clicking the animation widget button opens the widget [chromium] › compare/compare-mobile-test.spec.js:22:1 › Mobile comparison A|B toggle buttons are visible and only A is selected by default [chromium] › compare/compare-test.spec.js:20:1 › Animation is disabled when compare mode active [chromium] › compare/layer-dialog-test.spec.js:30:1 › Layer option features work in A|B mode === [chromium] › compare/layer-sidebar-test.spec.js:24:1 › Add AOD Layer to Layer Group A ========== [chromium] › compare/permalinks-test.spec.js:24:1 › Swipe mode and A|B state A are active and date is correct [chromium] › compare/timeline-test.spec.js:21:1 › Verify that A|B draggers are visible ========= [chromium] › events/event-filter-test.spec.js:40:1 › Default filtering includes last 120 days and all categories [chromium] › events/event-test.spec.js:20:1 › Make sure that 4 fire layers are not present in layer list: use mock [chromium] › events/events-mobile-test.spec.js:25:1 › Events populated in sidebar ============== [chromium] › global-unit/coordinate-format-test.spec.js:21:1 › Open page ======================= [chromium] › global-unit/global-unit-test.spec.js:28:1 › Global settings menu item opens global settings modal [chromium] › image-download/crosses-dateline-test.spec.js:20:1 › No dateline alert notification with message if not crossing dateline(s) [chromium] › image-download/formats-test.spec.js:34:1 › JPEG is the default ==================== [chromium] › image-download/global-select-test.spec.js:32:1 › Verify that global select is present and not selected [chromium] › image-download/initial-state-test.spec.js:31:1 › Check resolutions ================ [chromium] › image-download/lat-long-input-test.spec.js:31:1 › Check that image download inputs are hidden on initial load [chromium] › image-download/layers-test.spec.js:24:1 › List layers in draw order =============== [chromium] › image-download/projection-test.spec.js:28:1 › Geographic is EPSG:4326 ============= [chromium] › image-download/resolutions3413-test.spec.js:34:1 › In the arctic, top zoom levels is 5km [chromium] › image-download/resolutions4326-test.spec.js:34:1 › In geographic, top two zoom levels are 10km [chromium] › image-download/time-test.spec.js:26:1 › Image for today =========================== [chromium] › image-download/unsupported-test.spec.js:31:1 › Custom palettes are not supported dialog [chromium] › layers/layer-picker-mobile-test.spec.js:25:1 › Initial state indicates layer count [chromium] › layers/layer-picker-test.spec.js:22:1 › Layer picker shows categories when first opened [chromium] › layers/layers-sidebar-test.spec.js:48:1 › Toggle layer Info ======================= [chromium] › layers/layers-vector-test.spec.js:22:1 › Vector layer click does not show alert when all vector layers are clickable [chromium] › layers/options-test.spec.js:21:1 › Verify that settings button opens settings modal [chromium] › layers/recent-layers-mobile-test.spec.js:25:1 › Layer picker shows categories when first opened [chromium] › layers/recent-layers-no-local-storage-test.spec.js:22:1 › Verify that recent layers tab does not show when local storage is disabled [chromium] › layers/recent-layers-test.spec.js:22:1 › Layer picker shows categories when first opened [chromium] › location-search/location-search-mobile-test.spec.js:23:1 › Location Search component is visible by default [chromium] › location-search/location-search-test.spec.js:24:1 › Location Search component is visible by default [chromium] › measure/measure-test.spec.js:29:1 › Clicking the measure button opens the menu ==== [chromium] › modal/about-modal-test.spec.js:24:1 › About modal not open when URL param not present [chromium] › notifications/notify-test.spec.js:31:1 › No visible notifications with mockAlert parameter set to no_types [chromium] › palettes/disable-test.spec.js:18:1 › Verify that toggling class updates permalink and layer-legend [chromium] › projections/projections-test.spec.js:21:1 › Verify default page shows projection toolbar button in geographic projection map [chromium] › share/share-test.spec.js:23:1 › Clicking the share link button opens the share dialog [chromium] › smart-handoff/smart-handoff-test.spec.js:19:1 › Data tab is available and in default state when clicked [chromium] › timeline/date-selector-test.spec.js:20:1 › Verify subdaily default year, month, day, hour, minute date selector inputs [chromium] › timeline/layer-coverage-panel-test.spec.js:17:1 › Layer coverage is shown by default [chromium] › timeline/timeline-mobile-test.spec.js:22:1 › date.mob.init.2a: Before 3:00 UTC: load yesterdays date [chromium] › timeline/timeline-test.spec.js:24:1 › Dragger is visible ========================== [chromium] › tour/tour-test.spec.js:20:1 › Verify that all tour modals are present when the page is loaded [chromium] › ui/distraction-free-mode-test.spec.js:73:1 › Enabling distraction free mode with shortcut key hides UI elements [chromium] › ui/info-mobile-test.spec.js:23:1 › Mobile info toolbar is visible and contains valid mobile menu items [chromium] › ui/info-test.spec.js:20:1 › Info toolbar is visible and contains valid menu items = [chromium] › ui/toolbar-test.spec.js:20:1 › Info toolbar is visible and contains valid menu items [firefox] › animation/animation-test.spec.js:20:1 › Clicking the animation widget button opens the widget [firefox] › animation/gif-test.spec.js:25:1 › Clicking the animation widget button opens the widget [firefox] › animation/mobile-animation-test.spec.js:22:1 › Clicking the animation widget button opens the widget [firefox] › compare/compare-mobile-test.spec.js:22:1 › Mobile comparison A|B toggle buttons are visible and only A is selected by default [firefox] › compare/compare-test.spec.js:20:1 › Animation is disabled when compare mode active = [firefox] › compare/layer-dialog-test.spec.js:30:1 › Layer option features work in A|B mode ==== [firefox] › compare/layer-sidebar-test.spec.js:24:1 › Add AOD Layer to Layer Group A =========== [firefox] › compare/permalinks-test.spec.js:24:1 › Swipe mode and A|B state A are active and date is correct [firefox] › compare/timeline-test.spec.js:21:1 › Verify that A|B draggers are visible ========== [firefox] › events/event-filter-test.spec.js:40:1 › Default filtering includes last 120 days and all categories [firefox] › global-unit/coordinate-format-test.spec.js:21:1 › Open page ======================== [firefox] › global-unit/global-unit-test.spec.js:28:1 › Global settings menu item opens global settings modal [firefox] › image-download/crosses-dateline-test.spec.js:20:1 › No dateline alert notification with message if not crossing dateline(s) [firefox] › image-download/formats-test.spec.js:34:1 › JPEG is the default ===================== [firefox] › image-download/global-select-test.spec.js:32:1 › Verify that global select is present and not selected [firefox] › image-download/initial-state-test.spec.js:31:1 › Check resolutions ================= [firefox] › image-download/lat-long-input-test.spec.js:31:1 › Check that image download inputs are hidden on initial load [firefox] › image-download/layers-test.spec.js:24:1 › List layers in draw order ================ [firefox] › image-download/projection-test.spec.js:28:1 › Geographic is EPSG:4326 ============== [firefox] › image-download/resolutions3413-test.spec.js:34:1 › In the arctic, top zoom levels is 5km [firefox] › image-download/resolutions4326-test.spec.js:34:1 › In geographic, top two zoom levels are 10km [firefox] › image-download/time-test.spec.js:26:1 › Image for today ============================ [firefox] › image-download/unsupported-test.spec.js:31:1 › Custom palettes are not supported dialog [firefox] › layers/layer-picker-mobile-test.spec.js:25:1 › Initial state indicates layer count = [firefox] › layers/layer-picker-test.spec.js:22:1 › Layer picker shows categories when first opened [firefox] › layers/layers-sidebar-test.spec.js:48:1 › Toggle layer Info ======================== [firefox] › layers/layers-vector-test.spec.js:22:1 › Vector layer click does not show alert when all vector layers are clickable [firefox] › layers/options-test.spec.js:21:1 › Verify that settings button opens settings modal [firefox] › layers/recent-layers-mobile-test.spec.js:25:1 › Layer picker shows categories when first opened [firefox] › layers/recent-layers-no-local-storage-test.spec.js:22:1 › Verify that recent layers tab does not show when local storage is disabled [firefox] › layers/recent-layers-test.spec.js:22:1 › Layer picker shows categories when first opened [firefox] › location-search/location-search-mobile-test.spec.js:23:1 › Location Search component is visible by default [firefox] › location-search/location-search-test.spec.js:24:1 › Location Search component is visible by default [firefox] › measure/measure-test.spec.js:29:1 › Clicking the measure button opens the menu ===== [firefox] › modal/about-modal-test.spec.js:24:1 › About modal not open when URL param not present [firefox] › notifications/notify-test.spec.js:31:1 › No visible notifications with mockAlert parameter set to no_types [firefox] › palettes/disable-test.spec.js:18:1 › Verify that toggling class updates permalink and layer-legend [firefox] › projections/projections-test.spec.js:21:1 › Verify default page shows projection toolbar button in geographic projection map [firefox] › share/share-test.spec.js:23:1 › Clicking the share link button opens the share dialog [firefox] › smart-handoff/smart-handoff-test.spec.js:19:1 › Data tab is available and in default state when clicked [firefox] › timeline/date-selector-test.spec.js:20:1 › Verify subdaily default year, month, day, hour, minute date selector inputs [firefox] › timeline/layer-coverage-panel-test.spec.js:17:1 › Layer coverage is shown by default [firefox] › timeline/timeline-mobile-test.spec.js:22:1 › date.mob.init.2a: Before 3:00 UTC: load yesterdays date [firefox] › timeline/timeline-test.spec.js:24:1 › Dragger is visible =========================== [firefox] › tour/tour-test.spec.js:20:1 › Verify that all tour modals are present when the page is loaded [firefox] › ui/distraction-free-mode-test.spec.js:73:1 › Enabling distraction free mode with shortcut key hides UI elements [firefox] › ui/info-mobile-test.spec.js:23:1 › Mobile info toolbar is visible and contains valid mobile menu items [firefox] › ui/info-test.spec.js:20:1 › Info toolbar is visible and contains valid menu items == [firefox] › ui/toolbar-test.spec.js:20:1 › Info toolbar is visible and contains valid menu items [webkit] › animation/animation-test.spec.js:20:1 › Clicking the animation widget button opens the widget [webkit] › animation/gif-test.spec.js:25:1 › Clicking the animation widget button opens the widget [webkit] › animation/mobile-animation-test.spec.js:22:1 › Clicking the animation widget button opens the widget [webkit] › compare/compare-mobile-test.spec.js:22:1 › Mobile comparison A|B toggle buttons are visible and only A is selected by default [webkit] › compare/compare-test.spec.js:20:1 › Animation is disabled when compare mode active == [webkit] › compare/layer-dialog-test.spec.js:30:1 › Layer option features work in A|B mode ===== [webkit] › compare/layer-sidebar-test.spec.js:24:1 › Add AOD Layer to Layer Group A ============ [webkit] › compare/permalinks-test.spec.js:24:1 › Swipe mode and A|B state A are active and date is correct [webkit] › compare/timeline-test.spec.js:21:1 › Verify that A|B draggers are visible =========== [webkit] › events/event-filter-test.spec.js:40:1 › Default filtering includes last 120 days and all categories [webkit] › events/event-test.spec.js:20:1 › Make sure that 4 fire layers are not present in layer list: use mock [webkit] › events/events-mobile-test.spec.js:25:1 › Events populated in sidebar ================ [webkit] › global-unit/coordinate-format-test.spec.js:21:1 › Open page ========================= [webkit] › global-unit/global-unit-test.spec.js:28:1 › Global settings menu item opens global settings modal [webkit] › image-download/crosses-dateline-test.spec.js:20:1 › No dateline alert notification with message if not crossing dateline(s) [webkit] › image-download/formats-test.spec.js:34:1 › JPEG is the default ====================== [webkit] › image-download/global-select-test.spec.js:32:1 › Verify that global select is present and not selected [webkit] › image-download/initial-state-test.spec.js:31:1 › Check resolutions ================== [webkit] › image-download/lat-long-input-test.spec.js:31:1 › Check that image download inputs are hidden on initial load [webkit] › image-download/layers-test.spec.js:24:1 › List layers in draw order ================= [webkit] › image-download/projection-test.spec.js:28:1 › Geographic is EPSG:4326 =============== [webkit] › image-download/resolutions3413-test.spec.js:34:1 › In the arctic, top zoom levels is 5km [webkit] › image-download/resolutions4326-test.spec.js:34:1 › In geographic, top two zoom levels are 10km [webkit] › image-download/time-test.spec.js:26:1 › Image for today ============================= [webkit] › image-download/unsupported-test.spec.js:31:1 › Custom palettes are not supported dialog [webkit] › layers/layer-picker-mobile-test.spec.js:25:1 › Initial state indicates layer count == [webkit] › layers/layer-picker-test.spec.js:22:1 › Layer picker shows categories when first opened [webkit] › layers/layers-sidebar-test.spec.js:48:1 › Toggle layer Info ========================= [webkit] › layers/layers-vector-test.spec.js:22:1 › Vector layer click does not show alert when all vector layers are clickable [webkit] › layers/options-test.spec.js:21:1 › Verify that settings button opens settings modal = [webkit] › layers/recent-layers-mobile-test.spec.js:25:1 › Layer picker shows categories when first opened [webkit] › layers/recent-layers-no-local-storage-test.spec.js:22:1 › Verify that recent layers tab does not show when local storage is disabled [webkit] › layers/recent-layers-test.spec.js:22:1 › Layer picker shows categories when first opened [webkit] › location-search/location-search-mobile-test.spec.js:23:1 › Location Search component is visible by default [webkit] › location-search/location-search-test.spec.js:24:1 › Location Search component is visible by default [webkit] › measure/measure-test.spec.js:29:1 › Clicking the measure button opens the menu ====== [webkit] › modal/about-modal-test.spec.js:24:1 › About modal not open when URL param not present [webkit] › notifications/notify-test.spec.js:31:1 › No visible notifications with mockAlert parameter set to no_types [webkit] › palettes/disable-test.spec.js:18:1 › Verify that toggling class updates permalink and layer-legend [webkit] › projections/projections-test.spec.js:21:1 › Verify default page shows projection toolbar button in geographic projection map [webkit] › share/share-test.spec.js:23:1 › Clicking the share link button opens the share dialog [webkit] › smart-handoff/smart-handoff-test.spec.js:19:1 › Data tab is available and in default state when clicked [webkit] › timeline/date-selector-test.spec.js:20:1 › Verify subdaily default year, month, day, hour, minute date selector inputs [webkit] › timeline/layer-coverage-panel-test.spec.js:17:1 › Layer coverage is shown by default [webkit] › timeline/timeline-mobile-test.spec.js:22:1 › date.mob.init.2a: Before 3:00 UTC: load yesterdays date [webkit] › timeline/timeline-test.spec.js:24:1 › Dragger is visible ============================ [webkit] › tour/tour-test.spec.js:20:1 › Verify that all tour modals are present when the page is loaded [webkit] › ui/distraction-free-mode-test.spec.js:73:1 › Enabling distraction free mode with shortcut key hides UI elements [webkit] › ui/info-mobile-test.spec.js:23:1 › Mobile info toolbar is visible and contains valid mobile menu items [webkit] › ui/info-test.spec.js:20:1 › Info toolbar is visible and contains valid menu items === [webkit] › ui/toolbar-test.spec.js:20:1 › Info toolbar is visible and contains valid menu items 773 skipped

It looks like all of the tests didn't even run, which probably means that the binaries were not installed or were not installed correctly. In our `postinstall` script that runs at the end of `npm ci`, it should install the binaries locally on your computer which are required for the testing to work. Can you try it one more time and ensure that you perform `npm ci` after checking out to the `playwright-integration` branch?

**Comment by minniewong** [comment]
User error! I only got one failing test now.

  1 failed
    [firefox] › share/share-test.spec.js:95:1 › Clicking Shorten link is refused with links greater than 2048 characters

**Pull request merged**
