### PR TITLE
Update fire story color

### PR DESCRIPTION
**Pull request by minniewong**
## Description

Updated fire tour stories to reflect new colours and NOAA-20. 

## Further comments

If this is a relatively large or complex change, start a discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

## Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

**Comment by jasontk19** [comment]
I don't see where the color is changed?

**Comment by minniewong** [comment]
@jasontk19 changed color in the text of two tour stories, both in step 2 - "red" to "orange" and "red" to "orange or red"

**Comment by jasontk19** [comment]
Oh ok, I was thinking the color of the tour story box or something... got it.

**Comment by jasontk19** [comment]
Somewhat related... the FIRMS link in step 6 of the fires overview story doesn't take you to the same view seen in the tour (like it says): https://firms.modaps.eosdis.nasa.gov/map/?&_ga=2.260458253.1208088860.1598878371-1627262527.1592919469#z:8;c:-59.6,-7.0;t:adv-points;d:2019-07-25..2019-07-25;l:firms_viirs,firms_modis_a,firms_modis_t,fire_viirs_crtc

Screen Shot 2020-09-01 at 9 38 48 AM

**Comment by minniewong** [comment]
> Somewhat related... the FIRMS link in step 6 of the fires overview story doesn't take you to the same view seen in the tour (like it says): https://firms.modaps.eosdis.nasa.gov/map/?&_ga=2.260458253.1208088860.1598878371-1627262527.1592919469#z:8;c:-59.6,-7.0;t:adv-points;d:2019-07-25..2019-07-25;l:firms_viirs,firms_modis_a,firms_modis_t,fire_viirs_crtc
> 
> Screen Shot 2020-09-01 at 9 38 48 AM

@jasontk19 good catch! I have fixed it. Can you verify it works?

**Comment by jasontk19** [comment]
Looks great! 👍

**Pull request merged**
