### PR TITLE
Add classification toggle to vector products [WIP]

### LINKED ISSUE #2724: Add disable classification disable functionality to dams layer (vectors)
**What existing feature could be improved?**
Add disable classification disable functionality to dams layer (vectors). 
**Describe the improvement you'd like**
Should work how now-vector classification layers work
Screen Shot 2020-03-02 at 11 07 02 AM

### PR DESCRIPTION
**Pull request by Benjaki2**
## Description

Fixes #2724 

- [x] Change vector renderMode to use `image`
- [x] Add functionality for changing colors inside mapbox vector style expressions

## Further comments

If this is a relatively large or complex change, start a discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

## Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

**Comment by jasontk19** [comment]
I'm not seeing any classification toggles for vector layers on this branch 🤔 
Screen Shot 2020-03-16 at 9 04 31 AM

**Comment by Benjaki2** [comment]
Yikes... Made the config change in the `web/config/wv.json` for instantaneous dev and forgot to make the actual change in the real config. :smh:
Should be good to go now @jasontk19

**Comment by Benjaki2** [comment]
I don't know that it would be an easy addition for this PR. We have the custom pixel-replacing happening during the onTileLoad function https://github.com/nasa-gibs/worldview/blob/master/web/js/ol/lookupimagetile.js#L14-L52. 

Allowing caching in the response headers should fix the problem, which is something I believe is in the works on the GIBS side... We could also try to go in and replace the preexisting `tileImage` canvas `img` where it is stored in OL-land. However, we would need to keep a reference to the original image. It would be much easier if we could just rely on caching to solve the problem. Making a ticket to `investigate` further seems like a good plan of action for now.

**Comment by Benjaki2** [comment]
- [ ] Make work in A|B mode

**Comment by jasontk19** [comment]
This PR is looking pretty stale... should we close for now?

**Pull request closed without merging**
