### PR TITLE
Wv 2777 firms protected areas

### PR DESCRIPTION
**Pull request by PatchesMaps**
## Description

Replace existing Protected Areas layer with FIRMS-based version

## How To Test

1. `git checkout WV-2777-firms-protected-areas`
2. `npm run build`
3. `npm run watch`
4. go to this [link](http://localhost:3000/?v=-77.22856349787646,37.78362944421794,-72.84689854977414,40.30663674940418&l=World_Database_on_Protected_Areas,Reference_Labels_15m(hidden),Reference_Features_15m(hidden),Coastlines_15m,VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor&lg=true&t=2023-10-20-T18%3A34%3A38Z)
5. verify that the new layer loads and is visible at the maximum zoom level

### CODE REVIEW

**Comment by Tomcariello** [comment]
Should this show imagery when zoomed out? The current Protected Areas layer shows imagery when fully zoomed out but this implementation only shows the protected areas when zoomed in pretty far.

**Comment by PatchesMaps** [comment]
Unfortunately all of the tiles return 404's when zoomed out

**Comment by PatchesMaps** [comment]
> Should this show imagery when zoomed out? The current Protected Areas layer shows imagery when fully zoomed out but this implementation only shows the protected areas when zoomed in pretty far.

Unfortunately all of the tiles return 404's when zoomed out. Our point of contact with FIRMS is working on it from their end.

**Review by minniewong — COMMENTED** [review]
Looks good in Geographic projection at all zoom levels; there's an issue with Arctic and Antarctic. In the polar projections, it just displays all global PAs. Not sure if it's possible to reproject the geographic to polar; if not perhaps we should deactivate the PA layer for those projections.
Screenshot 2023-10-27 at 10 36 08 AM

**Comment by minniewong** [comment]
I get an error message when I switch from geographic to arctic:
Screenshot 2023-10-31 at 4 32 07 PM

**Comment by minniewong** [comment]
Screenshot 2023-10-31 at 4 33 09 PM
Since there's now "Terrestrial Protected Areas" and "Marine Protected Areas" can we add a blue box in the layer legend area?

**Comment by Tomcariello** [comment]
This looks pretty good to me but if I zoom [ALL the way in ](http://localhost:3000/?v=-64.50887450165791,10.171440082191191,-64.30851134247823,10.335411029456816&l=World_Database_on_Protected_Areas,Coastlines_15m,MODIS_Terra_Sea_Ice(hidden,disabled=1-2-3-4-5-6-7-8-9-10),MODIS_Terra_CorrectedReflectance_TrueColor&lg=true&t=2023-10-01-T18%3A17%3A41Z) the layer is not rendering. Should this layer continue to display imagery at the MAX zoom level?

**Review by ryanweiler92 — APPROVED** [review]

**Review by minniewong — APPROVED** [review]
Looks good!

**Pull request merged**
