### PR TITLE
Wv 2837 display currently selected preset

### PR DESCRIPTION
**Pull request by PatchesMaps**
## Description

> In the "Customize" menu for DDV layers, make it so that the currently selected preset is in a "selected" or "clicked" state.

## How To Test

1. `git checkout WV-2837-display-currently-selected-preset`
2. `npm ci && npm run watch`
3. Open this [link](http://localhost:3000/?v=-76.37172809794721,39.305032656143176,-74.86300080168131,40.17377319999999&l=Reference_Labels_15m,Reference_Features_15m,Coastlines_15m,OrbitTracks_Sentinel-2B_Descending,OrbitTracks_Sentinel-2A_Descending,HLS_Customizable_Sentinel(bandCombo=%257B%2522r%2522%253A%2522B07%2522%252C%2522g%2522%253A%2522B05%2522%252C%2522b%2522%253A%2522B04%2522%257D),HLS_Customizable_Landsat(hidden,bandCombo=%257B%2522r%2522%253A%2522B07%2522%252C%2522g%2522%253A%2522B05%2522%252C%2522b%2522%253A%2522B04%2522%257D),VIIRS_NOAA20_CorrectedReflectance_TrueColor,VIIRS_SNPP_CorrectedReflectance_TrueColor,MODIS_Aqua_CorrectedReflectance_TrueColor,MODIS_Terra_CorrectedReflectance_TrueColor&lg=true&t=2023-09-02-T23%3A02%3A13Z)
4. Click on layer settings
5. Click Customize
6. Select a preset and click Confirm Band Selection
7. Open the customize menu again
8. Verify that the preset you selected is still selected.

## PR Submission Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/main/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

## Merging

Please use the `squash and merge` commit method unless each commit in your branch is vital to the commit history of main.

@nasa-gibs/worldview

### CODE REVIEW

**Comment by minniewong** [comment]
The link in step 3 has default Bands 7, 5, 4 but is actually displaying Bands 8 ,4, 3.
Screenshot 2023-09-07 at 11 53 14 AM
Screenshot 2023-09-07 at 11 51 47 AM

**Comment by PatchesMaps** [comment]
Thanks @minniewong, I might have to remove the default preset to account for custom layer combinations.

**Comment by minniewong** [comment]
> Thanks @minniewong, I might have to remove the default preset to account for custom layer combinations.

That works - but we could also just change the default preset to the first custom layer combo, I'm not sure there was anything specific about the default preset that was chosen.

**Review by ryanweiler92 — CHANGES_REQUESTED** [review]
Everything looks and works great. You just need to remove a console log on line 56 of `band-selection-menu.js`

**Review by minniewong — APPROVED** [review]

**Review by ryanweiler92 — APPROVED** [review]

**Pull request merged**
