### PR TITLE
Fix tour scroll 

### LINKED ISSUE #2127: Scrolling in About page should maintain the header/title
Scrolling in the Tour modal and About page should behave more like the Layer picker where the header/title and close button are still viewable.

### LINKED ISSUE #2196: Tour modal will not scroll
**Describe the bug**
The Tour modal is no longer scrollable and the bottom is cut off.

**To Reproduce**
1. Load main page with a small monitor or screen size

**Expected behavior**
Should be able to scroll to the bottom of modal

**Screenshots**
Screen Shot 2019-10-02 at 12 08 10 PM

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: `develop`

**Additional context**
Probably related to a dependency update

### PR DESCRIPTION
**Pull request by Benjaki2**
## Description

Fixes #2196
Fixes #2127 

Tour won't scroll

- [x] Use simple scrollbar
- [x] Keep checkout box always visible at bottom of modal

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- [x] I have added necessary documentation (if applicable)
- [] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] Any dependent changes have been merged and published in downstream modules (if applicable)

## Further comments

If this is a relatively large or complex change, start a discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

@nasa-gibs/worldview

### CODE REVIEW

**Comment by Benjaki2** [comment]
@minniewong I believe that will fix it, since I was working off of the Dorian build  and it appears to work but it still shouldn't break like that with a different # of tiles. I will take another look

**Comment by Benjaki2** [comment]
@minniewong I think that is resolved now.

**Comment by jasontk19** [comment]
So I checked out this branch and ran it on top of a build from some older configs and also saw some versions of the alignment issue @minniewong saw:

Screen Shot 2019-10-03 at 10 58 21 AM

Looks great once I built with the most recent configs though.  I'm fine with postponing a fix to this until it actually matters (like when we add another tour story, if that causes it to appear again). 

Was there a separate ticket for changing the scroll behavior to be confined to within the modal?  I know we talked about this recently. If so we should tag it here and close it.

**Comment by edplato** [comment]
For Windows, I get a horizontal scroll (see greyish scroll bar at bottom).

image

**Comment by ZachTRice** [comment]
Probably just needs a few more pixels max-width to straighten it out. Do you know how much more extra max-width is needed before the horizontal bar goes away?

**Comment by edplato** [comment]
`1px` extra does the trick

**Comment by Benjaki2** [comment]
@jasontk19 I think we were talking about abandoning the bootstrap modal scrollbar going with this across the board. Not sure if we have and issue for that. It does look like this fixes #2127 .

@edplato I added `1px` to the `max-width`. Does it look good to go for you?

**Pull request merged**
