### PR TITLE
Make checkbox labels clickable

### LINKED ISSUE #2701: Labels next to checkboxes should toggle the checkbox
**Describe the bug**
There are several places in the app where we have checkboxes that the labels are not configured properly to allow clicking to enable/disable the checkbox.  We should identify all of these and fix them so that either the label or the checkbox can be clicked to update the value.

Known places:

* Tour dismiss checkbox
* Orbit tracks toggle in layer info modal
* ...

**Expected behavior**
Any label next to a checkbox should allow interaction to toggle the checkbox

### PR DESCRIPTION
**Pull request by jasontk19**
## Description

Fixes #2701 

* make all checkbox and switch labels clickable
* clean up modal styles for more consistency 
  * differentiate between header/body background with colors
  * subtle border and box shadow to distinguish modal from app in background
  * use consistent looking close icons across modals

### List of Affected Modals (to inspect and verify)
* Tour start
* Tour in progress
* Tour finished
* Layer settings
* Layer info
* “About” Worldview
* Product picker
* Feature info (comparison, events, vector etc)
* Info/Projection button dropdown
* Share modal
* Snapshot modal
* GIF modal
* Vector metadata modal

## Some Screenshots
Screen Shot 2020-07-21 at 12 58 06 PM
Screen Shot 2020-07-21 at 12 58 12 PM
Screen Shot 2020-07-21 at 12 58 56 PM
Screen Shot 2020-07-21 at 12 58 49 PM
Screen Shot 2020-07-21 at 12 58 20 PM
Screen Shot 2020-07-21 at 1 00 54 PM

@nasa-gibs/worldview

### CODE REVIEW

**Comment by minniewong** [comment]
Could you also add a space between "raster" and "(image)" in the first question of the vector features description box :)

**Comment by jasontk19** [comment]
> Looks good in all the places mentioned - I don't see any changes in data download, but I assume we won't touch it for now.
> Also just noticed an extra transparent bit on the bottom of the download GIF box. (tested in firefox and chrome)
> Screen Shot 2020-07-21 at 2 29 36 PM

Hmmm I am not seeing the issue in your screenshot after trying a few different sizes/shapes for a GIF (tall and narrow, short and wide, relatively square).  I did push a few changes to this branch that tweak this modal after I requested your review, I wonder if you pulled this branch before I pushed those changes?  

Since data download is going to be replaced soon, and since it uses a totally different set of components to render modals, I will leave those as is for now I think.

I've added the requested space to the vector modal 👍

**Comment by jasontk19** [comment]
Checkbox component in tour modal, for your consideration: 

Screen Shot 2020-07-22 at 1 33 10 PM

**Comment by jasontk19** [comment]
@edplato 

* Updated the tour start modal to use the checkbox component.  The orange default color was a bit distracting so I went with our gray style here.
* The console error was fixed, the warning is showing on `develop` and is not related to these changes
* There was a hover color change but i've upped the contrast between default and hover; take a look and see what you think.

**Pull request merged**
