### PR TITLE
WV-2775: Layer Threshold Combined Slider

### PR DESCRIPTION
**Pull request by christof-wittreich**
## Description
This converts the the two MIN and MAX sliders for Threshold in a layer's options to a single, two-sided slider instead.

## How To Test
1. `git checkout wv-2775-update-layerthresholdslider`
2. `npm ci`
3. `npm run watch`
4. Click the "Add Layers" button on the main sidebar on the right, and add any layer with a threshold option (for example, the Aerosol Index layer). Then, click the options sliders icon on the layer card to open the layer options window, and locate the thresholds slider.
5. Verify that the two-sided threshold slider functions the same as the existing two MIN and MAX threshold sliders do, by changing the low and high ends of the threshold and verifying that the correct change is seen on the layer.

### CODE REVIEW

**Comment by Tomcariello** [comment]
After modifying the threshold minimum value, if I copy & [load the permalink ](http://localhost:3000/?l=Reference_Labels_15m(hidden),Reference_Features_15m(hidden),Coastlines_15m,MODIS_Combined_Value_Added_AOD(min=0.155,max=0.59),VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor&lg=true&t=2023-08-09-T12%3A41%3A40Z)in a new browser window & access the options panel the minimum threshold slider is at the zero position even though it has a value greater than zero.

image

Once I adjust the maximum slider value the minimum position is corrected.

**Comment by Tomcariello** [comment]
This may be out of scope, but the styling in Firefox is off. 

image
image

**Comment by christof-wittreich** [comment]
@Tomcariello I believe I've fixed the issues you've mentioned in your comments now, if you could re-review it please

**Review by Tomcariello — APPROVED** [review]
This looks good!

This is probably out of scope/should be a new ticket but...

There is an existing bug in the permalink loading in production. This URL (http://localhost:3000/?l=Reference_Labels_15m(hidden),Reference_Features_15m(hidden),Coastlines_15m,MODIS_Combined_MAIAC_L2G_AerosolOpticalDepth(min=0.045,max=0.525),MODIS_Terra_CorrectedReflectance_TrueColor&lg=true&t=2023-08-10-T11%3A55%3A13Z) had the MAX threshold set to 0.525-0.530. Paste the URL to a new browser & notice the MAX setting is off by 1 tick - it loads at 0.520-0.525.

**Review by ryanweiler92 — APPROVED** [review]

**Pull request merged**
