### PR TITLE
Fix polar tour events

### LINKED ISSUE #2753: Events not showing after exiting tour
**Describe the bug**
Events not showing after exiting tour. If a user loads the main page, selects the **Pine Island Glacier** tour story and exits on the first step, then clicking the Events tab doesn't show event icons on the map.

**To Reproduce**
1. Go to main page and click on **Pine Island Glacier** tour story
2. Click 'X' to exit story
3. Click on 'Events' tab
4. Note no event icons on map

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, IE11

### PR DESCRIPTION
**Pull request by Benjaki2**
## Description

Fixes #2753

Event Markers not being shown when tour step causes change in Projection 

## Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

**Comment by edplato** [comment]
This fix looks good for the specified issue, but now I'm seeing a related? issue if you have the events tab selected in antarctic (can see the event markers) and start the **Pine Island Glacier** tour story then the event markers are retained even though the event tab is not selected.

**Comment by Benjaki2** [comment]
Good find @edplato !
I made that fix and did some more testing... And I _think_ it's looking good.

**Comment by edplato** [comment]
Looks to fix the issue and the above added case. I found one more case relating to this. If you go to a clean page, select antarctic, select events tabs, refresh page, and then start the Pine Island Glacier tour story the event markers remain.

It seems by the time the state gets to `web\js\map\natural-events\ui.js` after the above sequence then `events.active` is already set to false. Maybe `web\js\modules\tour\util.js` has a possible entry point to handle the state changes?

**Comment by Benjaki2** [comment]
related to #2766

**Comment by Benjaki2** [comment]
> Looks to fix the issue and the above added case. I found one more case relating to this. If you go to a clean page, select antarctic, select events tabs, refresh page, and then start the Pine Island Glacier tour story the event markers remain.

#2766 appears to have fixed that error.

**Pull request merged**
