### PR TITLE
Reset custom interval selector on tour step change without interval, or if delta is 1

### LINKED ISSUE #3389: Can't advance days in tour story when changing to a custom interval
- Go to the HLS tour, go to step 14 (which has set the time step to 5 day intervals)
- Then go to step 15 which is at 1 day interval, and change it to 5 Day as it appears in the menu
- Try to click the forward and back arrow, the date does not advance or go back 5 days

### PR DESCRIPTION
**Pull request by edplato**
## Description

Fixes #3389 .

- [X] Set update conditions to reset on tour step without interval, and reset if delta set to 1 (e.g. '1 day')

## Further comments

If this is a relatively large or complex change, start a discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

## Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

**Comment by jasontk19** [comment]
Noticed one weird thing that's not happening in prod:

1. Start in default app state
2. Change custom interval to `3 Day`, close modal.
3. Selector now says `3 Day` 
4. Change custom interval to `1 Day`, close modal.
5. Selector now says `CUSTOM` instead of `1 Day`

**Comment by edplato** [comment]
I removed the options for 1 day/month/year custom since that's a default interval option. It will reset to Custom if delta is 1.

**Comment by jasontk19** [comment]
I think that makes sense but, it looks weird to have it just say `CUSTOM` when you switch it to `1 Day` as a "custom" option.  I would expect it to show `1 Day`

**Comment by jasontk19** [comment]
For example:
Screen Shot 2021-03-01 at 2 09 37 PM

**Comment by edplato** [comment]
I'm getting what you're saying. I was mainly trying to avoid this:
image
I'll revert that part of the PR.

**Comment by jasontk19** [comment]
Agree that having "1 Day" in the list is not desirable since it's the same as "Day".  But in the current state, sometimes the selector says "1 Day" and sometimes it says "Custom" if you selected a custom "1 Day" interval, depending on the order you change things.  The inconsistency is just kinda quirky that's all.

**Review by jasontk19 — APPROVED** [review]
👍🏻

**Pull request merged**
