### PR TITLE
Wv 2375.build overhaul

### PR DESCRIPTION
**Pull request by ZachTRice**
## Description

Fixes WV-2375 

## How To Test

- Build the application, check for any build errors 
- With application built, spot check the application for differences to production

## Bugs found / to fix
- [x] Axios sometimes errors out with 404
- [X] E2E Chrome test fails on moveTo, moveToElement, getAttributes
This was a nightwatch config issue
- [x] E2E FireFox random test failures 
- [x] Fix layers/layers-sidebar-test in mac/chrome
- [x] Fix measure/measure-test in mac/chrome

### CODE REVIEW

**Review by ryanweiler92 — APPROVED** [review]

**Comment by minniewong** [comment]
> This built & ran fine but I noticed a behavior change in the Geostationary Imagery Tour.
> 
> When I run the "Geostationary Imagery Every 10 Minutes!" Tour, at slide 6 no imagery is loaded. I tested this on Windows & Mac & I see the same behavior on both platforms. I do see this imagery in production, SIT & the latest `develop` branch.

I'm seeing something specifically wrong with any tour step that has a GOES-East layer loaded, as well as just having GOES-East loaded. It seems not to be requesting the correct time. 
Compare l[ocalhost](http://localhost:3000/?v=-301.2386218472977,-144.12083408128944,295.6892097825228,124.147051912091&z=4&ics=true&ici=5&icd=10&l=Reference_Labels_15m(hidden),Reference_Features_15m(hidden),Coastlines_15m,GOES-East_ABI_Air_Mass,GOES-East_ABI_Band13_Clean_Infrared,GOES-East_ABI_Band2_Red_Visible_1km,GOES-East_ABI_GeoColor,VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor(hidden)&lg=true&t=2023-02-02-T01%3A30%3A53Z) to [prod](https://worldview.earthdata.nasa.gov/?v=-301.65182970866783,-144.56345175485686,296.65679260380966,124.32498127588386&z=4&ics=true&ici=5&icd=10&l=Reference_Labels_15m(hidden),Reference_Features_15m(hidden),Coastlines_15m,GOES-East_ABI_Air_Mass,GOES-East_ABI_Band13_Clean_Infrared,GOES-East_ABI_Band2_Red_Visible_1km,GOES-East_ABI_GeoColor,VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor(hidden)&lg=true&t=2023-02-02-T01%3A30%3A53Z). Locally, you can only see the imagery on the far right (for the previous day) and in prod you can see both the current day and previous day's imagery.

**Review by minniewong — CHANGES_REQUESTED** [review]
There's also an issue with the palettes. For example, Flood should show Surface water as blue, Flood as red, Insufficient Data as grey. In this branch, it's showing no water as blue, surface water as red and flood as grey.
Screen Shot 2023-02-08 at 10 21 43 AM

**Comment by ZachTRice** [comment]
@minniewong can you check the Geostationary Imagery Tour and palettes issue again. These should be solved.

**Review by minniewong — APPROVED** [review]
Thanks for those fixes - I didn't find anything else specific to this PR!

**Review by Tomcariello — APPROVED** [review]
My reported problem is fixed. This looks good!

**Pull request merged**
