### PR TITLE
Add flex styling and minor changes to alert notification for consistent mobile/desktop style

### PR DESCRIPTION
**Pull request by edplato**
## Description

Add flex styling to inner components of alert notification and add mobile friendly styling for consistent mobile/desktop style.

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- [ ] I have added necessary documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [ ] Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

**Comment by jasontk19** [comment]
Pulled this up in iPhone 7 randomly on Browserstack and got this weird cramped alignment:
Screen Shot 2019-10-08 at 3 24 02 PM

Screen Shot 2019-10-08 at 3 18 38 PM


Otherwise, when it wraps to the next line, the horizontal alignment of "Read more..." feels off.  It's neither fully left or right justified which seems unusual.

**Comment by edplato** [comment]
Can you provide any other details on browser/version for debugging? The two iPhone 7's I checked on Browserstack don't look like that.

**Comment by jasontk19** [comment]
It was Safari on an emulated iPhone 7.  For some reason I am not able reach localhost on the "real" devices.  I wouldn't worry too much about that one if you're not seeing it otherwise.

**Comment by Benjaki2** [comment]
I can second seeing that on browserstacks - iphone 8

**Comment by Benjaki2** [comment]
related to #2248

**Comment by edplato** [comment]
Pandora's box of mobile alert style fun. I think the geostationary alert is important, or else I'd say just get rid of all mobile alerts. Will rework this fix.

**Comment by jasontk19** [comment]
Looks good now!

I have one minor nitpick, consider it optional.  At certain widths the "Read more ..." gets split across lines:
Screen Shot 2019-10-09 at 8 50 15 AM

**Comment by jasontk19** [comment]
Honestly.... I'd be OK if we just removed the "Read more..." bit.  I think it's pretty intuitive that you click on a notification like this to get more info.

**Comment by edplato** [comment]
@jasontk19 I agree, will remove that text

**Comment by jasontk19** [comment]
There is now some extra space on mobile to the left/right of the text/close button. Clicking here neither opens the modal or dismisses it.  Probably want to eliminate this dead space.
Screen Shot 2019-10-09 at 11 54 30 AM

**Pull request merged**
