### PR TITLE
Add now button to timeline controls

### LINKED ISSUE #3315: "Today" or "Now" button/shortcut
**Is your feature request related to a problem? Please describe.**
As discussed (frequently) in the past, there are times when you'd like to instantly change the date to be "today" rather than having to manually update the year, month, day, etc.

**Describe the solution you'd like**
To test the waters, we can start by adding a keyboard shortcut to avoid allocating the screen real estate and design cycles.  

**Additional context**
Note that there is a distinction between "today" and "now", in that "today" implies just changing the date to today's date... but "now" also changes the time of day to "right now" which could be useful for geostationary layers which are updated every 10 minutes.  TBD which one we want to do.

### PR DESCRIPTION
**Pull request by edplato**
## Description

Fixes #3315  .

Main:
- [x] Add now button to timeline controls that selects the current `appNow` date.
- [x] Add `SHIFT-T` Now shortcut and update about page with shortcut.
- [x] Disable right arrow if less than selected interval (e.g., 1 day) available to advance in the future.
- [x] Add timeline dragger max date to end of timeline date to allow dragging dragger to exact timeline end date limit - at some point since it was calculated based on position/pixels this value could be floored so the dragger wasn't at the exact timeline end date limit.
- [x] Resize animation button to fit and polish various related timeline styles.

Note: 
- [x] The default app now date is set to 40 minutes prior to the current time to account for the geostationary latency. This allows the now button to be used with geostationary layers and retrieve the most updated imagery as expected.
- [x] Future time layers will allow future layer coverage, but `appNow` will still adhere to now (i.e., new Date() minus 40 minutes), so the timeline dragger can be in the future beyond `appNow` and the now button can still be activated to "go back to" now.
- [x] Since `now=` test url parameter will override `appNow` and use the parameter date as `appNow`, `appNow` will be prevented from updating.

Other:
- [x] Update animation widget minimized default position to accommodate side height.
- [x] Add min-width for `wv-content` to affect page content.
- [x] Update About page to make wider, smaller text, and make shortcut keys more prominent before scrolling #3654 
- [x] Update timeline axis to reposition focus on finish animating to event date change.
- [x] Revise sidebar nav tabs to use new tooltips. Revise tooltip names to match other tooltip first letter only capitalization style.
- [x] Remove selectDate dispatch for natural events that resulted in a double firing of selectDate which is handled conditionally in `web\js\map\natural-events\natural-events.js`.
- [x] Remove unused `showSubdaily` and `modalView` deprecated test parameters from docs.

## How To Test

1. Change date and use NOW button and/or `SHIFT-T` shortcut to select `appNow` date

## PR Submission Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/main/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

**Review by minniewong — COMMENTED** [review]
When I loaded geostationary, I was initially confused as to why the timeline didn't show the time to the "real now", but realised that was they way you intended it to work. Glad to see it auto loads the next time increment automatically, so the "now" arrow becomes highlighted. I wonder if we could add some info to the tooltip, or in the about/shortcuts section to explain what "now" means when you have a geostationary layer loaded.

**Comment by minniewong** [comment]
Is the blue availability line also supposed to update? I loaded the page around 16:40 and just clicked on the now button to take me to 17:31
Screen Shot 2021-08-09 at 2 16 43 PM

**Comment by jasontk19** [comment]
> When I loaded geostationary, I was initially confused as to why the timeline didn't show the time to the "real now", but realised that was they way you intended it to work. Glad to see it auto loads the next time increment automatically, so the "now" arrow becomes highlighted. I wonder if we could add some info to the tooltip, or in the about/shortcuts section to explain what "now" means when you have a geostationary layer loaded.

Maybe "now" isn't the best wording for the tooltip for this reason.  Maybe "most recent" or "latest"... something along those lines.

**Review by jasontk19 — APPROVED** [review]
Other than the thing that Minnie found (which didn't seem to happen in the tab I left open) this looks good to me!

**Comment by edplato** [comment]
Updated tooltip text to "Latest available date".

**Comment by minniewong** [comment]
> Updated tooltip text to "Latest available date".

Should it be "Latest available date/time"? If one has geostationary loaded, "latest available date" still doesn't convey that it's not showing imagery up to the current time.

**Review by minniewong — APPROVED** [review]

**Pull request merged**
