### PR TITLE
WV-2355: Add Landsat 9 and TRMM orbit tracks

### PR DESCRIPTION
**Pull request by minniewong**
## Description

Fixes WV-2355

Add Landsat-9 and TRMM Orbit Tracks

@nasa-gibs/worldview

### CODE REVIEW

**Comment by minniewong** [comment]
Awaiting updates to GIBS GC (incorrect start date for Landsat 9) and GIBS layer-metadata (Update typos and add making TRMM ongoing=false)

**Comment by minniewong** [comment]
I don't know what the conflicts are :(

**Comment by jasontk19** [comment]
Did you want to update the Land_Water_Map layer title here too?

**Comment by minniewong** [comment]
> Did you want to update the Land_Water_Map layer title here too?

i forgot - done!

**Review by jasontk19 — APPROVED** [review]
Looks good, let's squash and merge!

**Comment by MaxQRocketDude** [comment]
At long last TRMM has been added!  That’s been in the GIBS backlog for a long time. :)

**Pull request merged**
