### PR TITLE
WV-3226 Look and Feel Changes

### PR DESCRIPTION
**Pull request by christof-wittreich**
## Description
This update changes the style and look of some things on the WV landing screen, including font, color, icons, and the tour story boxes. See the design [here](https://bugs.earthdata.nasa.gov/secure/attachment/103121/wv_hds_comp_3a.png). Note the eye icons in the design are intentionally being ignored in favor of our current eye icons.

## How To Test
1. `git checkout wv-3226-look-and-feel`
2. `npm ci`
3. `npm run watch`
4. Open a fresh instance of Worldview
5. Confirm that many things on the front page matches the designs
6. Confirm that functionality of basic features still works

### CODE REVIEW

**Comment by Tomcariello** [comment]
The add layers button is not rendering correctly.

image

**Comment by Tomcariello** [comment]
Are the timeline icons updating as well? The icons in the mockup (bottom in this pic) look thinner than what is in WV currently.

image

**Comment by Tomcariello** [comment]
The font & checkboxes in the layer picker have changed. Was this intentional?

image

**Comment by Tomcariello** [comment]
The "Select Entire Globe" checkbox used to be orange. Was this change intended?

image

**Review by minniewong — COMMENTED** [review]
The checkboxes seem to differ between browsers. Left is Chrome (check mark is lower in the box), right is Firefox (check mark is centered in the box).
Screenshot 2024-08-30 at 10 53 11 AM

**Comment by christof-wittreich** [comment]
Fonts and checkboxes are meant to be changed site-wide, yes

**Comment by Tomcariello** [comment]
Everything I mentioned previously looks good. The only thing I see if that the checkboxes in the RECENT tab of the layer picker fill solid blue without the white checkmark. It looks like the SVG element is not being loaded.

image

**Comment by christof-wittreich** [comment]
@Tomcariello This should be fixed now too

**Comment by minniewong** [comment]
It's looking good! Could you also change the font thickness to match the other thickness for the body of the "About" section, and the hover text for the Tour Story modal?
Screenshot 2024-09-04 at 11 44 29 AM
Screenshot 2024-09-04 at 11 44 10 AM

**Comment by minniewong** [comment]
These checkboxes aren't center aligned in Chrome and Firefox. (the ones reported earlier are correctly centered now)
Screenshot 2024-09-04 at 11 46 03 AM

**Review by Tomcariello — APPROVED** [review]

**Comment by minniewong** [comment]
Looks like the arrow background need to be made a bit more transparent?

Screenshot 2024-09-05 at 12 13 01 PM

**Comment by minniewong** [comment]
Another really small nit - I think because the "Layer Coverage" text went onto a new line (it used to be all on one line), the whole Layer availability panel got pushed down into the timeline. Maybe just move the "i" and toggle elements over a bit to the right so that "Layer Coverage" can remain on one line?

Screenshot 2024-09-05 at 12 21 32 PM

**Comment by minniewong** [comment]
When you minimize the layer list, there is some overlap that is not present in Prod. I'm guessing because the title is bigger now. We should replicate prod and have a tiny space between the title/logo and the layer list
Screenshot 2024-09-05 at 12 32 15 PM
Prod:
Screenshot 2024-09-05 at 12 32 30 PM

**Review by minniewong — APPROVED** [review]

**Pull request merged**
