### PR TITLE
Update dockerfile

### PR DESCRIPTION
**Pull request by jasontk19**
## Description

The dockerfile is used to set up the build environment in Bamboo.  This updates the Python and Node versions to match what we are testing against in our Github Actions CI.

### CODE REVIEW

**Comment by jasontk19** [comment]
Here is the build in Bamboo based on this branch to see it working: `WV-SWP1560-3`

**Review by edplato — APPROVED** [review]
I think it looks good. Did you find out what `yum install -y https://centos7.iuscommunity.org/ius-release.rpm && \` was doing? It looks like a dead link and doesn't seem to be causing any build issues with removing it.

**Comment by jasontk19** [comment]
@edplato I'm not really sure what that RPM was supposed to be but, I had to remove it because it was failing the build since the file doesn't exist at that URL anymore.

**Review by Benjaki2 — APPROVED** [review]
I am still having trouble building it on my machine but the code looks good to me. There is probably something wrong with my version of docker. If it works on your computer and bamboo... I say, go for it!

**Comment by jasontk19** [comment]
> I am still having trouble building it on my machine but the code looks good to me. There is probably something wrong with my version of docker. If it works on your computer and bamboo... I say, go for it!

Hmmm yeah it seems to work fine locally... What errors are you getting?

**Comment by Benjaki2** [comment]
> > I am still having trouble building it on my machine but the code looks good to me. There is probably something wrong with my version of docker. If it works on your computer and bamboo... I say, go for it!
> 
> Hmmm yeah it seems to work fine locally... What errors are you getting?

Working now after restarting my terminal.

**Pull request merged**
