### PR TITLE
add cygnss soil moisture, change clear sky dates, fix typos

### LINKED ISSUE #3432: Updated start date for Clear Sky Confidence.
FYI, GC has been updated for Clear Sky confidence.

(1) For the NOAA20 Day and Night Clear Sky Confidence layers the temporal coverage start date is listed as 2018-03-17 but it should actually be 2018-02-17. On the Worldview side of things, its actually listed as 2012-03-01 (the SNPP one) which is also wrong.

This is now fixed on GIBS OPS.

### LINKED ISSUE #3433: Added CYGNSS Soil Moisture SDR STD v1.0
PODAAC ICD - Line 31

### PR DESCRIPTION
**Pull request by minniewong**
## Description

Fixes #3433 
Fixes #3432  .

- [x] Adds CYGNSS Soil Moisture layer and description
- [x] Update NOAA-20 Clear Sky Confidence start date to 17 Feb 2018.
- [x] fix typos

[If this is a relatively large or complex change, start a discussion by explaining why you chose the solution you did and what alternatives you considered, etc...]

## How To Test

[Provide whatever information a reviewer might need to know in order to verify that the changes made in this PR are working as expected. If there are special build steps that need to be taken in order to get these changes to run (building while on a separate branch, running `npm ci`, etc) include them here.]

- For bugfixes: What steps need to be taken in the UI to verify the bug is fixed?
- For enhancements and features: What is the expected functionality being added/modified? How can a reviewer verify this?

1. Open with these URL parameters
2. ...
3. Verify expected result

## PR Submission Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

**Review by edplato — COMMENTED** [review]
Is CYGNSS Soil Moisture still active? The GC is showing it ending in 2020, but not sure if there is future coverage coming?

**Comment by minniewong** [comment]
> Is CYGNSS Soil Moisture still active? The GC is showing it ending in 2020, but not sure if there is future coverage coming?

I checked with GIBS - It will be updated in batches, but is definitely still being updated, albeit with very long latencies.

**Review by edplato — APPROVED** [review]
🛰️👍🏽

**Comment by minniewong** [comment]
> 🛰️👍🏽

@edplato Thanks for making me check. We checked with the data provider and it indeed WON'T be updated so I've added the inactive: true flag.

**Pull request merged**
