### PR TITLE
WV-2493 Charting Mode

### PR DESCRIPTION
**Pull request by Tomcariello**
## Description
Create interactive prototype in Worldview of rapid analysis imagery statistics UI that demonstrate end-to-end capabilities of imagery statistics. Initial work has been done utilizing the PO.DAAC ImageStat API. We would like to include this preliminary implementation into the release behind a feature flag (disabled by default).

Frontend charting implementation should be designed so that different charting APIs, e.g PO.DAAC imagestat, VEDA, SentinelHub Statistical API, can be used to display the same types of information without needing to have a substantially different core charting codebase.

NOTE: This feature is disabled by default. To enable, open `/config/default/common/features.json` & set `charting `to `true` & then run `npm run build`.

## How To Test
NOTE: This API often has CORS errors that prevent success from localhost. I have been using the CORS Everywhere extension for Firefox to get around that problem. 'Allow CORS' extension for Chrome also works. You should be on the VPN as well.

- git checkout WV-2493-simple-statistics
- npm install
- npm run build (if you change the charting mode availability)
- npm run watch
- Add any layers with a palette (for instance, Aqua/Airs Carbon Monoxide (L2, 500 hPa, Night) or Aura/OMI Aerosol Index). 
- Click the Start Charting button to test the feature.

## Usage:
- Click the pencil to draw an Area of Interest (AOI). If you do not specify an AOI, it will default to the full map.
- Select a date. On start of chart mode, the date from the timeline will be your start date. Click the calendar icon to bring up the charting mode date selector.

NOTE: You should keep your Networking tab open as the API sometimes (regularly) responds with an internal error 500. In that case, you can try changing your AOI and/or reducing your time range to increase your odds of success.

- 'Single Date' mode --> Modal with mean/median/max/stddev for that date. Takes 3-5 seconds typically.
- 'Date Range ' mode--> Dynamic chart of mean/median/max/stddev across 10 steps from the start date to end date. This can easily take 30 seconds + to get data.

@nasa-gibs/worldview

### CODE REVIEW

**Comment by PatchesMaps** [comment]
```
Request URL: https://d1igaxm6d8pbn2.cloudfront.net/get_stats?_type=date&timestamp=2023-07-26&steps=6&layer=AIRS_L2_Carbon_Monoxide_500hPa_Volume_Mixing_Ratio_Night&colormap=AIRS_Carbon_Monoxide_Volume_Mixing_Ratio.xml&bbox=36.81029193175935,-77.68162928362965,40.30936346128196,-74.49134534440225&bins=10
Request Method: GET
Status Code: 200
Referrer Policy: strict-origin-when-cross-origin
```
Are we going to need to proxy these requests in order to not get CORS errors?

**Comment by PatchesMaps** [comment]
`user-select: none;` on the date selectors would be nice to have but not necessary.

Screenshot 2023-07-28 at 1 40 36 PM
Screenshot 2023-07-28 at 1 38 00 PM

**Comment by Tomcariello** [comment]
> ```
> Request URL: https://d1igaxm6d8pbn2.cloudfront.net/get_stats?_type=date&timestamp=2023-07-26&steps=6&layer=AIRS_L2_Carbon_Monoxide_500hPa_Volume_Mixing_Ratio_Night&colormap=AIRS_Carbon_Monoxide_Volume_Mixing_Ratio.xml&bbox=36.81029193175935,-77.68162928362965,40.30936346128196,-74.49134534440225&bins=10
> Request Method: GET
> Status Code: 200
> Referrer Policy: strict-origin-when-cross-origin
> ```
> 
> Are we going to need to proxy these requests in order to not get CORS errors?

I have updated the PR with some more info regarding the CORS errors during testing. Essentially you need to be 1) on the VPN & 2) using a CORS browser extension (Allow CORS for chrome, or CORS Anywhere for Firefox) to get successful requests.

In the longer term, the API hosting will be modified to eliminate the CORS issue.

**Comment by Tomcariello** [comment]
> 

Yea, that's a good idea but I don't think it belongs in this PR. Feel free to make another ticket (or just PR it) if you'd like.

**Review by PatchesMaps — APPROVED** [review]

**Review by ryanweiler92 — APPROVED** [review]

**Pull request merged**
