### PR TITLE
WV-2552: Upgrade Node To 18.14.0

### PR DESCRIPTION
**Pull request by ryanweiler92**
## Description

Upgrading Node from v16.18.0 to 18.14.0

### CODE REVIEW

**Review by Tomcariello — APPROVED** [review]

**Review by ZachTRice — CHANGES_REQUESTED** [review]
node v18.14.0 will not work in the Dockerfile because RHEL 7 (centos 7), does not support a version of glibc recent enough to install node 18.x.

**Review by ZachTRice — APPROVED** [review]

**Comment by ZachTRice** [comment]
centos7 has been upgraded to rhel9 so you can rebase on develop and upgrade node in the Dockerfile

**Review by ZachTRice — CHANGES_REQUESTED** [review]
Can you also update .github/workflows/ci-cd.yml and change "node: [16]" to node: [18]

**Comment by ryanweiler92** [comment]
> Can you also update .github/workflows/ci-cd.yml and change "node: [16]" to node: [18]

I've pulled in the latest changes in develop which include the upgrade to rhel9. I have also updated the ci-cd.yml file to the node 18.

**Review by ZachTRice — APPROVED** [review]

**Pull request closed without merging**
