### PR TITLE
Layer metadata improvements

### PR DESCRIPTION
**Pull request by jasontk19**
## Description

Addresses #3606 

Compile individual layer metadata into the category/source metadata shown in "browse" mode of the product picker.  All Corrected Reflectance metadata was updated as an example of how we would need to update the existing metadata to work with this approach.

### Measurements Checklist

- [x] Absolute Dynamic Topography
- [x] Aerosol Albedo
- [x] Aerosol Index
- [x] Aerosol Optical Depth
- [x] Albedo
- [x] Amphibian Richness
- [x] Areas of No Data (mask)
- [x] Blue Marble
- [x] Brightness Temperature
- [x] Carbon Dioxide
- [x] Carbon Monoxide
- [x] Chlorophyll A
- [x] Cirrus Reflectance
- [x] Clear Sky Confidence
- [x] Cloud Albedo
- [x] Cloud Effective Radius
- [x] Cloud Fraction
- [x] Cloud Liquid Water
- [x] Cloud Multi Layer Flag
- [x] Cloud Optical Thickness
- [x] Cloud Phase
- [x] Cloud Pressure
- [x] Cloud Top Height
- [x] Cloud Top Temperature
- [x] Cloud Water Path
- [x] Convective Rainwater Source
- [x] Corrected Reflectance
- [x] Cyclone Hazard
- [x] Dams
- [x] Drought Hazard
- [x] Dust
- [x] Earth at Night
- [x] Evaporation
- [x] FPAR
- [x] Faraday Rotation
- [x] Featured - Fires and Thermal Anomalies
- [x] Featured - Land Surface Reflectance
- [x] Featured - Precipitation
- [x] Featured - Sea Surface Temperature
- [x] Featured - Socioeconomic Data Vectors
- [x] Fires and Thermal Anomalies
- [x] Flood Hazard
- [x] Flood
- [x] Forests Mangrove
- [x] Freeze-Thaw
- [x] Frozen Area
- [x] Geostationary
- [x] Global Digital Elevation Map
- [x] Gross Primary Productivity
- [x] Heterotrophic Respiration
- [x] Human Built-up And Settlement Extent
- [x] Human Footprint
- [x] Human Impacts
- [x] Ice Surface Temperature
- [x] Ice Velocity Antarctica
- [x] Ice Velocity Greenland
- [x] Impervious Surface
- [x] Isotropic Kernel Parameters
- [x] Land Cover
- [x] Land Surface Reflectance
- [x] Land Surface Temperature
- [x] Landslide Hazard
- [x] Latitude Longitude Lines
- [x] Leaf Area Index
- [x] Lightning
- [x] Liquid Water Equivalent
- [x] Mammal Richness
- [x] Methane
- [x] Net Ecosystem CO2 Exchange
- [x] Net Migration
- [x] Nitric Acid
- [x] Nitrogen Dioxide
- [x] Nitrous Oxide
- [x] Open Water Latent Energy Flux
- [x] Orbital Track
- [x] Outgoing Radiation
- [x] Ozone
- [x] Particulate Matter
- [x] Photosynthesis
- [x] Photosynthetically Available Radiation
- [x] Population Density
- [x] Power Plants Nuclear
- [x] Precipitation Estimate
- [x] Precipitation Rate
- [x] Radiance
- [x] Radiation
- [x] Reference Map
- [x] Relative Humidity
- [x] Reservoirs
- [x] Sea Ice Brightness Temperature
- [x] Sea Ice
- [x] Sea Surface Currents
- [x] Sea Surface Height Anomalies
- [x] Sea Surface Salinity
- [x] Sea Surface Temperature Anomalies
- [x] Sea Surface Temperature
- [x] Settlements
- [x] Sigma0
- [x] Snow Cover
- [x] Snow Depth
- [x] Snow Extent
- [x] Snow Mass
- [x] Snow Water Equivalent
- [x] Soil Moisture
- [x] Soil Temperature
- [x] Solar Induced Chlorophyll Fluorescence
- [x] Sulfur Dioxide
- [x] Surface Albedo
- [x] Surface Flux
- [x] Surface Pressure
- [x] TOA Albedo
- [x] TOA Flux
- [x] Temperature
- [x] Urban Expansion
- [x] Urban Extents
- [x] Vegetation Indices
- [x] Vegetation Light Use Efficiency
- [x] Volcano Hazard
- [x] Water Bodies
- [x] Water Vapor
- [x] Wind Speed

### CODE REVIEW

**Comment by minniewong** [comment]
@jasontk19 I just noticed that when you search for a layer the layer description set up should match the layer description that you see when you click on the "i" in the layer list (individual layer description + measurement description). Currently, it only shows the layer description.

**Comment by minniewong** [comment]
Completed updates to layer descriptions! 
@jasontk19 Would it be possible to make the description for the individual layer (when you search for a layer) to be individual layer description + measurement description?

**Comment by jasontk19** [comment]
@minniewong Nice work, thats a lot of layers!  I'll take a look at the change you mentioned now.

**Comment by jasontk19** [comment]
@Benjaki2 Can you take a quick look at this when you get a chance?  We want to get it merged soon since it's holding up any future layer description edits and keeps getting conflicts from other PRs which had changes to those files.

**Review by Benjaki2 — APPROVED** [review]
The JS looks good and looks like its working 👍

**Pull request merged**
