### PR TITLE
Migrate to OL6

### LINKED ISSUE #1949: Migrate from OL5 -> OL6
relates to #1923 
**Is your feature request related to a problem? Please describe.**
It is aways good to keep up to date with dependencies  and we need OL6 to enhance performance of vector layers

**Additional context**
It seems like a rather seamless merge aside from problems with the `swipe` compare mode.

**Todo**
- [x] Fix swipe
- [x] Replace graticule with new graticule layer class
- [x] Fix spy
- [x] Get Vector orbit tracks to work

### PR DESCRIPTION
**Pull request by Benjaki2**
## Description

Fixes #1949
 [OL 6.0 release notes](https://github.com/openlayers/openlayers/releases/tag/v6.0.0)
- [X] Migrate to ol6
- [x] Remove a lot of graticule logic in `map/ui.js` and interpret graticule as a layer. (t was a separate ol.component before 6.0)
- [x] Make Vector-layer breakpoint higher for feature-dense layers
- [x] change event listeners from `precompose` to `prerender`

## Further comments

* Look at new graticules -> ?`v=-168.826674456628,-69.68189318262525,283.9294774273213,80.61830477884972&l=Graticule,VIIRS_SNPP_Thermal_Anomalies_375m_Day,Reference_Labels(hidden),Reference_Features(hidden),Coastlines,VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor`

* A|B testing should be a priority

## Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

**Comment by edplato** [comment]
Nice! Still reviewing, but I encountered an issue with `opacity` now needing to be a number and we're using a string a few places in `map/ui.js` and `map/layerbuilder.js` that is causing an error. The error can be seen be adding the latitude/longitude layer and changing the opacity.

**Comment by edplato** [comment]
This may actually be helpful around the map extents with a few tweaks, but it's different from our current version so I want to bring it to your attention. The latitude/longitude lines extend beyond map extent at a greater zoom level:

image

**Comment by Benjaki2** [comment]
> Nice! Still reviewing, but I encountered an issue with `opacity` now needing to be a number and we're using a string a few places in `map/ui.js` and `map/layerbuilder.js` that is causing an error. The error can be seen be adding the latitude/longitude layer and changing the opacity.

Nice find!

**Comment by Benjaki2** [comment]
@rboller It turned out to be quick fix!

**Comment by Benjaki2** [comment]
> This may actually be helpful around the map extents with a few tweaks, but it's different from our current version so I want to bring it to your attention. The latitude/longitude lines extend beyond map extent at a greater zoom level:
> 
> image

Good call. I was able to limit it by specifying the layer extent.

**Comment by Benjaki2** [comment]
Screen Shot 2020-08-10 at 6 55 17 PM

Updated graticule labels

**Comment by rboller** [comment]
Glad to hear that and thanks @Benjaki2!

**Pull request merged**
