### PR TITLE
WV-2303: Replace OL graticule layer with new WMTS layer

### PR DESCRIPTION
**Pull request by Benjaki2**
## Description

Fixes #WV-2303
- [x] Update measurement config
- [x] update layer config
- [x] update layer-order json
- [x] Update metadata

[If this is a relatively large or complex change, start a discussion by explaining why you chose the solution you did and what alternatives you considered, etc...]

## How To Test

[Provide whatever information a reviewer might need to know in order to verify that the changes made in this PR are working as expected. If there are special build steps that need to be taken in order to get these changes to run (building while on a separate branch, running `npm ci`, etc) include them here.]

- For bugfixes: What steps need to be taken in the UI to verify the bug is fixed?
- For enhancements and features: What is the expected functionality being added/modified? How can a reviewer verify this?

1. Open with these URL parameters
2. ...
3. Verify expected result

## PR Submission Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/main/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

**Review by minniewong — CHANGES_REQUESTED** [review]
Seems like latitude labels are missing north of the equator. In this example, you see 15 S every few grid squares, but there isn't the corresponding 15 N every few grid squares.
Screen Shot 2022-05-11 at 4 05 45 PM

**Comment by minniewong** [comment]
There are no lat/long labels in Arctic (but there are labels in Antarctic)
Screen Shot 2022-05-11 at 4 10 37 PM

**Comment by minniewong** [comment]
For the preview image in the layer description, it might be better to include the coastlines outline, or land/water map

**Comment by minniewong** [comment]
Southern portion of the map is missing grid lines after 50S.

Screen Shot 2022-05-11 at 4 15 45 PM

**Comment by minniewong** [comment]
Maybe we should move the layer out of it's own measurement "Latitude Longitude Lines" and move it into "Reference Map"

**Comment by Benjaki2** [comment]
> There are no lat/long labels in Arctic (but there are labels in Antarctic). The lines also seem much fainter in Arctic/Antarctic compared to Geo
> 
> Screen Shot 2022-05-11 at 4 10 37 PM

Polar graticules have not been updated.

**Comment by Benjaki2** [comment]
> Southern portion of the map is missing grid lines after 50S.
> 
> Screen Shot 2022-05-11 at 4 15 45 PM

 I think this merits a postponement of the layer release 😞

**Comment by minniewong** [comment]
The Arctic Polar graticule in Prod has labels though 🤔  https://go.nasa.gov/3yw8CGK

**Comment by Benjaki2** [comment]
> The Arctic Polar graticule in Prod has labels though 🤔 https://go.nasa.gov/3yw8CGK

Seeing same thing locally at that URL
Screen Shot 2022-05-11 at 4 42 49 PM


http://localhost:3000/?v=-6971032.813390179,-3055789.6676127044,7777013.294287797,3790598.228796269&p=arctic&l=Graticule_15m,Reference_Labels_15m(hidden),Reference_Features_15m(hidden),Coastlines_15m,VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor&lg=true&t=2022-05-11-T19%3A30%3A58Z

**Comment by minniewong** [comment]
oh i just can't see the labels without any imagery underneath....

**Comment by minniewong** [comment]
oh i just can't see the labels in Arctic without any imagery underneath....

**Review by minniewong — COMMENTED** [review]
Could you update the preview image so it shows some landmasses or coastlines? and maybe some of the lat/long labels

**Comment by Benjaki2** [comment]
@minniewong I added a zoomed in image with the land/water layer in the background.

**Review by minniewong — APPROVED** [review]
🌐

**Pull request merged**
