### PR TITLE
WV-2222: Handle granule animation

### PR DESCRIPTION
**Pull request by jasontk19**
## Description

* Granule layer requests can complete much faster than other layers due to how little of the map is covered by imagery.  For this reasons, the request times were under the minimum request time we were filtering out when calculating average request times to determine the animation buffer size.
* Instead of filtering out minimum request times, replace very short request times with a defined minimum so we can't end up in a scenario where there are no request times to make calculations on.

## How To Test

* Checkout `wv-2228-config` branch
* npm run build
* Checkout `wv-2222-2` branch
* `npm run watch`

Here are a few test links with different time intervals:

### Swath-at-a-time
http://localhost:3000/?v=-157.67582306496837,-207.06684752843876,229.40823518764688,204.67224628166792&z=4&ics=true&ici=5&icd=102&as=2019-09-23-T00%3A00%3A00Z&ae=2019-09-24-T23%3A50%3A00Z&l=VIIRS_NOAA20_CorrectedReflectance_TrueColor_Granule_v1_NRT,Coastlines_15m&lg=true&al=true&av=10&ab=on&t=2019-09-22-T22%3A54%3A00Z

### Granule-at-a-time
http://localhost:3000/?v=-157.67582306496837,-207.06684752843876,229.40823518764688,204.67224628166792&z=4&ics=true&ici=5&icd=6&as=2019-09-23-T05%3A10%3A00Z&ae=2019-09-24-T03%3A50%3A00Z&l=VIIRS_NOAA20_CorrectedReflectance_TrueColor_Granule_v1_NRT,Coastlines_15m&lg=true&al=true&av=10&ab=on&t=2019-09-23-T07%3A10%3A00Z

### Ten Minute Intervals
http://localhost:3000/?v=-232.10321165414558,-207.06684752843876,303.8356237768241,204.67224628166792&z=4&ics=true&ici=5&icd=10&as=2019-09-23-T05%3A10%3A00Z&ae=2019-09-24-T03%3A50%3A00Z&l=VIIRS_NOAA20_CorrectedReflectance_TrueColor_Granule_v1_NRT,Coastlines_15m&lg=true&al=true&av=10&ab=on&t=2019-09-23-T10%3A10%3A00Z

### CODE REVIEW

**Comment by minniewong** [comment]
Is there a config branch I should use so i can see the granule imagery?

**Comment by jasontk19** [comment]
> Is there a config branch I should use so i can see the granule imagery?

Update description.  Same as last time should work.

**Comment by Benjaki2** [comment]
Code updates look good, but seeing the same issues as @minniewong.

**Review by minniewong — APPROVED** [review]
🚀  Animations are running smoothly!

**Comment by jasontk19** [comment]
There is still a timing issue specific to granule animations even when I bring in the animation timing improvements from WV-2154.  I suggest we get that PR reviewed/merged by itself while I try to work out the timing issue with granules in this PR.

**Comment by jasontk19** [comment]
Ok it was more straightforward than expected, granule animation timing should be fixed here now.

**Comment by minniewong** [comment]
Animations run at the correct speed now too :)

**Review by Benjaki2 — APPROVED** [review]
💯

**Pull request merged**
