### PR TITLE
Add SEDAC vector layers to "Socioeconomic" layergroup

### LINKED ISSUE #3510: Consider assigning SEDAC vector layers to a single "Socioeconomic" layer group
**What existing feature could be improved?**
Currently each layer lives in its own group, which isn't helpful when grouping since there is only 1 layer per group.

Screen Shot 2021-05-14 at 10 06 53 AM

### PR DESCRIPTION
**Pull request by jasontk19**
## Description

Fixes #3510

@nasa-gibs/worldview

### CODE REVIEW

**Comment by jasontk19** [comment]
Are there other layers that we should add to this group? There are lots of other small groups like "Human Footprint" which it might makes sense to consolidate here.

**Review by minniewong — COMMENTED** [review]
Not sure if it's weird to have vector and non-vector layers in the same group, but others that could possibly go in the socioeconomic layergroup could be (basing this on the layers that are singles):
Human Built-up and Settlement Extent, Impervious Surface, Urban Extents,

**Comment by jasontk19** [comment]
> Not sure if it's weird to have vector and non-vector layers in the same group, but others that could possibly go in the socioeconomic layergroup could be (basing this on the layers that are singles):
> Human Built-up and Settlement Extent, Impervious Surface, Urban Extents,

Personally I don't think it's too weird if they're vector or not since the grouping is more based on what kind of data the layer represents rather than how it is represented.  I will add these other layers to the group!

**Review by minniewong — APPROVED** [review]
Looks great!

**Pull request merged**
