### PR TITLE
WV-3237 Alert users if snapshot exceeds GRANULE_LIMIT

### PR DESCRIPTION
**Pull request by PatchesMaps**
## Description

> Alert users if snapshot exceeds GRANULE_LIMIT

## How To Test

1. `git checkout WV-3237-exceed-snapshot`
2. `npm run watch`
3. Open this [link](http://localhost:3000/?v=-353.40938621902797,-198.58423316002302,321.3109507141554,189.14568268178897&z=4&ics=true&ici=5&icd=6&l=VIIRS_NOAA20_CorrectedReflectance_BandsM3-I3-M11_Granule,VIIRS_NOAA20_CorrectedReflectance_TrueColor_Granule,VIIRS_SNPP_CorrectedReflectance_BandsM3-I3-M11_Granule,VIIRS_SNPP_CorrectedReflectance_BandsM11-I2-I1_Granule,VIIRS_NOAA20_CorrectedReflectance_BandsM11-I2-I1_Granule(count=30),VIIRS_SNPP_CorrectedReflectance_TrueColor_Granule(count=30),Coastlines_15m&lg=true&t=2024-08-04-T19%3A21%3A00Z).
4. Open the snapshot modal.
5. Verify that the warning appears in the modal.

## PR Submission Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/main/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

## Merging

Please use the `squash and merge` commit method unless each commit in your branch is vital to the commit history of main.

@nasa-gibs/worldview

### CODE REVIEW

**Comment by Tomcariello** [comment]
I don't think this is related to your work, but I keep getting "Invalid value for GRANULE_DATES" for a bunch of WVS requests.

**Comment by Tomcariello** [comment]
Do we want to this to calculate once at the time of the snapshot start? Or should it be calculated as the snapshot selection window is adjusted? I may have lots of granules on screen but if I only have a couple granules in my snapshot selection the warning doesn't apply.

**Comment by PatchesMaps** [comment]
> Do we want to this to calculate once at the time of the snapshot start? Or should it be calculated as the snapshot selection window is adjusted? I may have lots of granules on screen but if I only have a couple granules in my snapshot selection the warning doesn't apply.

We currently don't have the ability to send only the granules intersecting the snapshot selection. All of the granules loaded get sent to the server regardless of what the snapshot extent is focused on. So with the current functionality it makes the most sense to calculate this at the time of the snapshot start. If we want to add/change the functionality to only send the granules intersecting the snapshot bounding box then it would make the most sense to calculate this whenever the bounding box changes. I think that would be a story separate from this one though.

**Comment by PatchesMaps** [comment]
> I don't think this is related to your work, but I keep getting "Invalid value for GRANULE_DATES" for a bunch of WVS requests.

@Tomcariello Can you create a new story/ticket to address the error you're seeing?

**Comment by Tomcariello** [comment]
> If we want to add/change the functionality to only send the granules intersecting the snapshot bounding box then it would make the most sense to calculate this whenever the bounding box changes. I think that would be a story separate from this one though.

Understood. We should definitely create a ticket to see if we can only send granules that are included in the snapshot selection area.

**Review by Tomcariello — APPROVED** [review]

**Review by christof-wittreich — APPROVED** [review]

**Pull request merged**
