### PR TITLE
Merge `feature-pwa` into `release-3.21.0`

### PR DESCRIPTION
**Pull request by jwhurley1**
Merge `feature-pwa` into `release-3.21.0`.

### CODE REVIEW

**Comment by jasontk19** [comment]
Can we rebase this with the release branch?

**Comment by jwhurley1** [comment]
> Can we rebase this with the release branch?

Done!

**Comment by jasontk19** [comment]
So I opened this in Safari on my iPhone 12 and chose "Add to Home Screen" which, it did.  But, the new icon was not used and instead the icon is just a screenshot of the app (like it is by default)

**Comment by jasontk19** [comment]
This PR doesn't appear to include the changes from https://github.com/nasa-gibs/worldview/pull/3849

**Comment by jwhurley1** [comment]
Hmm ok.  Lemme try again

**Comment by jasontk19** [comment]
Some things we should probably address before this goes into a release:

- No loading screen showing on iPhones
- Bottom buttons can be too close to the edges on some phones (particularly newer iPhones) and the swipe bar to switch apps can get in the way
- In landscape mode, if you open the product picker, the Layers/Events tabs and the chevrons to collapse this menu are all difficult to press since they are so small and right against the edge of the screen.  I think touch events that happen right at the edge of the screen are often interpreted as the beginning of a swipe down motion and so aren't passed through to the browser

**Comment by jasontk19** [comment]
I just pushed the most recent updates to the GIBS UAT instances for `feature-pwa`.  Things that should be tested in both landscape and portrait orientations:

* Sidebar open/close
* Sidebar sizing with comparison mode on/off 
* Compare AB button placement
* Animation button placement
* Timeline date changes

Also it's likely that embed mode was affected so we should check that as well for any issues.

**Review by minniewong — COMMENTED** [review]
Polar Rotate buttons are missing

**Review by jasontk19 — APPROVED** [review]

**Pull request merged**
