### PR TITLE
Make compatible with Node LTS

### PR DESCRIPTION
**Pull request by Benjaki2**
## Description

Fixes #Wv-2212

Make compatible with Node LTS
- [x] update node-sass
- [x] Update eslint & some rules
- [x] Update node version in docker file
@nasa-gibs/worldview

### CODE REVIEW

**Comment by Benjaki2** [comment]
> 

I am not seeing this warning

**Comment by jasontk19** [comment]
Which version of node and npm are you using?  I am on:
```
➜  worldview git:(wv-2212) npm --version
8.5.4
➜  worldview git:(wv-2212) node --version
v16.14.0
```

I can poke around some and try to figure out what's causing this but it's kind of an issue for me since it floods the terminal to the point of pushing any previous output off the visible screen.

**Comment by Benjaki2** [comment]
node -> v16.14.0
npm -> v8.3.1

**Comment by jasontk19** [comment]
This change suppresses the message for me: https://github.com/babel/babel/issues/11622#issuecomment-634458299

**Review by jasontk19 — CHANGES_REQUESTED** [review]
:shipit:

**Pull request merged**
