### PR TITLE
Add vscode directory and settings

### LINKED ISSUE #1141: Ignore vscode directory
**Is your feature request related to a problem? Please describe.**
When using VSCode, a `.vscode` folder is often created. We need to add this folder to our `.gitignore` file so that this folder and it's contents are not accidentally committed.

**Describe the solution you'd like**
Add `.vscode` to `.gitignore`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by ZachTRice**
## Description

Commit `.vscode` folder & settings with rules that align with our lint rules.

Fixes #1141

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- [x] I have added necessary documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works (if applicable)
- [x] Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

**Comment by mike-mcgann** [comment]
.vscode directory there is fine. Those are for workspace settings that should apply to everyone working on that project and placing tabsize settings there might be a good idea. Personal settings go elsewhere outside the repo. I think the issue is more of one of the plugins wanting to automatically update that file with something if I recall.

**Comment by ZachTRice** [comment]
Yeah, my folder settings are blank but the folder gets created nonetheless and keeps trying to sneak into other commits. 

You're right, it could be beneficial to set a few items in this file based on our lint rules, i.e. tab settings. Shall I commit the file instead with tabs set to 2 spaces? We can add rules as needed later.

**Comment by mike-mcgann** [comment]
Here are ones that I use that could be useful in the workspace settings:

```json
{
    "files.trimTrailingWhitespace": true,
    "[javascript]": {
        "editor.tabSize": 2
    },
    "[json]": {
        "editor.tabSize": 2
    },
}
```

**Comment by ZachTRice** [comment]
Great, I have updated the PR to include the .vscode directory and these rules.

**Pull request merged**
