### PR TITLE
prevent glitchy vector rendering onZoom #2840

### LINKED ISSUE #2840: Vector point rendering for macOS chrome 80/81 is unreliable
**Describe the bug**
The Dams vector point layer appears to render unreliably. The vector points flicker in and out some complete tiles seem go missing at certain zoom levels.

**To Reproduce**
1. Go to '?v=-129.13381015637736,-58.88861311392172,100.35338772893672,70.37722256991536&l=GRanD_Dams,Reference_Labels(hidden),Reference_Features(hidden),Coastlines,VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor'
2. zoom in and out
3. See error

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: CHROME v80 v81

**Additional context**
This seems to be the result of a chrome update for macOS only.

### PR DESCRIPTION
**Pull request by Benjaki2**
## Description

Half Fixes #2840
The points no longer flicker in and out but there are a few tiles that are still not rendered properly in outer zooms

- [x] Replaced vector tile [renderMode](https://openlayers.org/en/v5.3.0/apidoc/module-ol_layer_Vector-VectorLayer.html) with `image` as opposed to `vector`
- [x] Make getCapabilities `vectorStyles` be overwritten by local styles
- [x] Adjust styles of dams layer

## Further comments

If this is a relatively large or complex change, start a discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

## Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

**Comment by jasontk19** [comment]
I still see quite a bit of flickering as I zoom in/out but it does seem better than how it behaves in prod right now.

**Comment by Benjaki2** [comment]
Yeah, it's definitely not perfect. The main difference is that this version seems to work when you are zoomed in. The question is... is it enough of an enhancement to merit this patch? I'm going to start working on the WMS fix. Maybe I can get that in quickly

**Comment by Benjaki2** [comment]
The real problem with the WMS solution is that it would be touching a lot of code.

**Comment by Benjaki2** [comment]
@edplato Good call. I had tried to do `git checkout package-lock.json` since I didn't make and changes there but must have did a rm instead 🤷‍♂️. Should be good now.

**Comment by jasontk19** [comment]
Ok I made the mistake of not rebuilding before deploying.  It looks a lot better than what is in production though as you said there are completely missing points at certain zoom levels.  I'd say it's worth getting the fix in for this release.

**Pull request merged**
