### PR TITLE
Vector Orbit Tracks

### LINKED ISSUE #2279: Orbit labels are cut off at dateline
**Describe the bug**
Orbit labels are cut off at dateline
relates to openlayers/ol-mapbox-style#221
**Expected behavior**
Orbital labels should be repositioned so that they are visible
**Screenshots**
image

### PR DESCRIPTION
**Pull request by Benjaki2**
## Description

Replace WMS orbit tracks with vector orbit tracks

Fixes #2279 

- [x] Fix issue where vector styles are base off of default mapbox proj and use current proj and update all styles accordingly 
- [x] Customize `ol-mapbox-style` library to avoid cut-off labels by tile edges
- [x] Update Orbit track styles for each label
- [x] Update Orbit track layer configs  
- [x] Make the vector dialog follow orbit tracks features as you click on them (`modalShouldFollowClicks` in layer config)
- [x] Prevent from being able to click on orbit track line (can only click points and text) (`clickDisabledFeatures` in layer config)
- [x] Use package-patch plugin instead of forked `ol-mapbox-style` lib
- [x] fix hls bug
- [x] make wms/vector split
- [x] make labels larger
[If this is a relatively large or complex change, start a discussion by explaining why you chose the solution you did and what alternatives you considered, etc...]

## How To Test

[Provide whatever information a reviewer might need to know in order to verify that the changes made in this PR are working as expected. If there are special build steps that need to be taken in order to get these changes to run (building while on a separate branch, running `npm ci`, etc) include them here.]

- For bugfixes: What steps need to be taken in the UI to verify the bug is fixed?
- For enhancements and features: What is the expected functionality being added/modified? How can a reviewer verify this?

1. Make sure styles for vector layers look good (especially orbit tracks)
2.  Make sure vector layer interactions work well (especially orbit tracks)
3. Check that vector layers work with WVS

## PR Submission Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/main/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

**Comment by mcechini** [comment]
Is there a test instance deployed somewhere pointing to GIBS production that I can use to verify?

**Comment by mcechini** [comment]
And do we need a PR against GIBS for updated vector styles to be worked simultaneously?

**Comment by Benjaki2** [comment]
> Is there a test instance deployed somewhere pointing to GIBS production that I can use to verify?

There isn't currently a test instance but you can use a local build to verify against PROD. I will work on getting a test instance up.

**Review by edplato — APPROVED** [review]
JS and the various JSON I checked look good. I have some styling issues I want to bring to your attention, but not certain how many are known/existing:

1. Cutoff orbit tracks at point of dateline wrap (http://localhost:3000/?v=-238.33910722540054,17.873486092072223,-131.9479955017298,81.62919868343708&l=OrbitTracks_Aqua_Ascending,Reference_Labels_15m(hidden),Reference_Features_15m(hidden),Coastlines_15m,VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor&lg=true&t=2021-07-27-T14%3A52%3A30Z):
image

2. Unstyled grey points (minor points only or all?) It seemed more apparent when zooming in/out and the map is repainting, but at second look they seem to persist at certain higher zoom levels:
image

3. Vector hand pointer
  A. Button covers longer category labels (e.g., Descending/Night)
  image
  B. Button is never disabled at higher zoom levels like for thermal anomalies.

**Comment by Benjaki2** [comment]
@edplato Thanks for the feedback

1. I don't think that issue is something we can resolve on our side that might be more of a question for @mcechini 
2. I'm not able to replicate this one. Could you provide a link? What is the browser you are using?
3.
   a. I will for on this.
   b. I think that we decided to keep orbit tracks as vector layers in the outer zooms since clicking on these in outer zooms could be helpful and there are not too many features for any one layer.

**Comment by edplato** [comment]
@Benjaki2 
For no. 2. I am seeing this in Chrome - here is a link (http://localhost:3000/?v=-195.79223103715168,-56.41065208978327,1.4833107585139231,43.15184791021673&l=OrbitTracks_Aqua_Ascending,Reference_Labels_15m(hidden),Reference_Features_15m(hidden),Coastlines_15m,VIIRS_NOAA20_CorrectedReflectance_TrueColor(hidden),VIIRS_SNPP_CorrectedReflectance_TrueColor(hidden),MODIS_Aqua_CorrectedReflectance_TrueColor(hidden),MODIS_Terra_CorrectedReflectance_TrueColor&lg=true&t=2021-07-30-T18%3A34%3A05Z). It seems like at any higher zoom levels there are the grey blocks and then when zoomed in enough they are overlaid with the minor orbit track points.

Completely unrelated, but I just ran into an issue where I copied that link over to Firefox to check there and the orbit tracks won't render and it gave me this error:
image
image

**Comment by Benjaki2** [comment]
@edplato I did a `distclean` and `rebuild` and this looks fine on my machine. Does it look like the `package-patch` plugin is install correctly on your `install`?

**Comment by edplato** [comment]
Everything appears to be installed right. To make things a little more confusing, the issue seems to be limited to when the browser window is on my second monitor only. I'm not seeing this with same links `develop`. I tested on my other computer with same second monitor and no issues, so I think it's a non-issue and not to worry about unless it comes up again from another source.

For reference, the above error was for Firefox. Here is an error I get for Chrome (both browser errors on second monitor only - main monitor is fine):
image
image

**Comment by Benjaki2** [comment]
@edplato I added a change that I think might fix it. 🤞

**Comment by edplato** [comment]
@Benjaki2 That fixed the Chrome error being thrown. The Firefox one remains the same. From my research it may be related to an eventListener and/or Worker.

**Comment by minniewong** [comment]
I'm also getting errors (Chrome): 
Screen Shot 2021-08-05 at 10 44 29 AM

**Review by minniewong — COMMENTED** [review]
Looks pretty good! just a couple of comments:
1. I'd suggest making the attribute information box a little less wide if possible - make it just fit the content.
2. It's a little laggy zooming in and out of the map, especially if you have more than one set of tracks loaded.

**Comment by Benjaki2** [comment]
> Looks pretty good! just a couple of comments:
> 
> 1. I'd suggest making the attribute information box a little less wide if possible - make it just fit the content.
> 2. It's a little laggy zooming in and out of the map, especially if you have more than one set of tracks loaded.

Making the modal dynamic in size would be pretty tough to do with the way our modal works at this point. that would require serious refactoring. A couple other options are... 

1. Making the dialog smaller for all vector products (I think this is a good option since it looks fine small for all products)
2. Specifying the width by vector layer type (`thermal anomolies`, `orbit tracks` etc...) and choosing the largest width from a list of clicks points (since numerous layers can be clicked a one time).

**Review by mcechini — APPROVED** [review]
I think we're good here.

**Review by jasontk19 — APPROVED** [review]

**Comment by MaxQRocketDude** [comment]
👏 👏

**Pull request merged**
