### PR TITLE
3067 fix social links

### PR DESCRIPTION
**Pull request by jasontk19**
## Description

Fixes # 3067

### CODE REVIEW

**Comment by jasontk19** [comment]
@edplato I think it's because we are doing those asynchronously rather than as the direct result of a user click: https://stackoverflow.com/questions/9514698/bypass-popup-blocker-on-window-open-when-jquery-event-preventdefault-is-set

**Comment by jasontk19** [comment]
Ok I think I see why we were previously trying to do `window.open` to a blank page and then set the location after .... https://stackoverflow.com/a/32908311/1132892

I'll update this.

**Comment by edplato** [comment]
Interesting, that makes sense. Good catch on proposed solution.

**Comment by jasontk19** [comment]
I think the real bug here was just that `status_code` is not part of the bitly response anymore... Anyway, it all seems to be working properly now.

**Pull request merged**
