### PR TITLE
Move ext scripts to dependencies key

### PR DESCRIPTION
**Pull request by localjo**
* Removed browser shim where not needed
* Imported dependencies where they are used
* Added dependencies to the `dependencies` key of package.json so they are part of our dependency graph
* Use npm installed version of dependencies instead of /ext directory

Still need to:
- [x] Remove `d3` global var
- [x] Figure out the correct way to include `isotope`
- [x] Move cache.js to dependencies
- [x] Import dependency CSS files from `node_modules`
- [x] Replace `browserify-css` with `postcss` npm script
- [x] Delete unneeded files from /ext directory
- [x] Remove dead code from Gruntfile

### CODE REVIEW

**Comment by Benjaki2** [comment]
@localjo the `browser`key does not work with files inside of `node_modules` directory (strange, I know). Also, remember we talked about keeping the that `ext/` version of `d3` for the time being as we are dependent on a forked version for the time being.

**Comment by localjo** [comment]
Looks like there's an issue with the `d3` version we're using depending on `jsdom` which depends on `contextify` which breaks `npm install`. So I guess we're going to have to stick with `d3` in `/ext` until we can update to not use the fork anymore.

**Comment by localjo** [comment]
For reference, the d3 version we're using is basically 3.4.11 plus the changes in this commit: https://github.com/d3/d3/pull/2019/files

**Comment by Benjaki2** [comment]
I'm seeing console errors with `jQuery.easing` not being a method (I assume this is a jQuery-ui thing) along with `icheck`

**Comment by localjo** [comment]
@Benjaki2 Thanks. I'll look into that. Can you give me more details about what line you're seeing that error on and what actions cause it? 

Also, don't spend too much time debugging this yet. I'll tag you and Zach when it's ready for review, but it's only half done right now.

**Comment by localjo** [comment]
I think this branch, in it's current state is an improvement and all of the changes work. However, I want to make some changes to the CSS bundling to align this more with our goals.

I used `browserify` to bundle the CSS, but when I wanted to add some more CSS transforms (auto-prefixing, specifically), I realized I wanted to use `browserify-postcss`, which could essentially be swapped in as-is, but then I realized that we talked about wanting to use libraries directly via npm scripts instead of using wrappers.

That should also be a pretty easy change at this point. I've got it mostly working locally with this script;

```bash
postcss ./web/css/main.css --use postcss-import --output ./web/build/wv.css
```

The only thing that's not working is relative paths for `font-awesome` font files. I had to resolve that problem for `browserify-css` as well, and I can use [`postcss-assets-rebase`](https://github.com/devex-web-frontend/postcss-assets-rebase) in this case. I just need to figure out how to configure that plugin. I think I'll need to move away from using the CLI in npm scripts to using the JS api like we're doing with browserify. Fairly straightforward, but I might not finish it before the holiday weekend.

**Comment by localjo** [comment]
See the top comment for all of the items this PR accomplishes. The two unfinished items can probably be saved for later on in #503, since they're related to the final build process.

The only changes should be related to the JS and CSS bundles, but I'm not sure if any of that broke the string replacement tasks. We'll also need to figure out how to enable "watch" mode at the right times so that it doesn't block other build scripts from running. And finally, we'll want to figure out exactly where/how the final built assets should be located and if they should be in the same place on both dev and production.

All of the outstanding items could be figured out later in a separate PR, and I'd like to move forward with getting this merged so we're all working from the same base.

@Benjaki2 and @ZachTRice go ahead and review this and let me know what you think.

**Comment by localjo** [comment]
To get this running, you'll probably have to do these steps;
```
rm -rf node_modules
npm install
npm link worldview-components
npm run build
npm start
```

**Comment by localjo** [comment]
I agree with those thoughts about CSS. Another idea worth considering is that we can actually `import` CSS files in JS. A common pattern that builds on the idea of renaming CSS files to have a 1:1 correlation with JS modules is to get rid of the single entry point CSS file and move the CSS files into the same folder as the JS module they apply to and then `import`ing them in the JS module. The bundler (whether Browserify, Webpack or something else) can then extract them and group them into a single bundle or inject them into the document using a `<style>` tag. I think that change and some of the others you suggested should be saved for another project when we can focus on our ideal CSS organization, but the changes in this PR enabling CSS bundling lay the foundation for us to be able to do that easily later.

**Pull request merged**
