### PR TITLE
WV-1990: Flood Tour Story

### PR DESCRIPTION
**Pull request by minniewong**
## Description

Fixes WV-1990

Review the Flood Tour Story entitled "Assessing Floodwaters". 

@nasa-gibs/worldview

### CODE REVIEW

**Comment by Tomcariello** [comment]
Some minor text/copy stuff to start with:
In the "View Description" window of **Flood (3-Day Window)** the link to the **User Guide** fails to load.

I see a couple places where I want to say "clouds" or "cloud cover" instead of "cloud" but I can certainly be wrong about the grammar:

- In Step 2 of 7, "...areas of insufficient data (usually due to **cloud**)."
- In Step 6 of 7, "showing how **cloud** initially obscured much of the flooding. **Cloud is** represented by grey 'insufficient data' pixels."

In Step 7 of 7, "yellow" is singular but "whites" is plural. Is this intentional? "...areas in yellow to whites, which correspond directly to the floodwaters overlaid in red and..."

**Comment by Tomcariello** [comment]
Something is wacky when you complete this Tour Story. This seems to be unique to this Story; I poked around with the others & was unable to recreate this error for any other Tour Story. 

I identified 3 ways to recreate this issue:

- Load the Flood tour story
- Cycle forward to Step 7 of 7
- Cycle back to Step 6 of 7
- Cycle forward to Step 7 of 7 again --> "Cannot read properties of undefined (reading 'custom')"

And Method #2 to reproduce:
- Load the Flood tour story
- Complete the Flood tour story
- Re-access the Tour Screen (the behavior is the same whether you select "More Stories" or reload the modal via "Info" --> "Explore" to get back to the Tour screen)
- Select ANY story EXCEPT Intro to Worldview (this only matters because Intro to Worldview is only 1 Step long)
- Try to advance to Step 2 --> "Cannot read properties of undefined (reading 'custom')"

And Method #3 to reproduce:
- Load the Flood tour story
- Complete the Flood tour story
- Re-access the Tour Screen (the behavior is the same whether you select "More Stories" or reload the modal via "Info" --> "Explore" to get back to the Tour screen)
- Select Intro to Worldview
- Complete Intro to Worldview
- Re-access the Tour Screen & select any Tour--> "Cannot read properties of undefined (reading 'custom')"

**Comment by minniewong** [comment]
@Tomcariello I've addressed the grammar and I removed the custom palette from the population density layer on Step 7, and that seems to have fixed the problem you reported. Please test again to check :)

**Review by ryanweiler92 — APPROVED** [review]
This looks great to me, everything seems to be working well. A note to my future self and anyone else who reads this -- You can only check/work on tour stories with `npm run watch` and NOT `npm run watch:debug:devtools`. The stories are extremely heavy on the dev tools and will crash the browser.

**Comment by Tomcariello** [comment]
@minniewong Grammar updates look great. While the previously reported crashes are fixed I found another one:
- Start & complete the new Flood Tour
- Select "More tours"
- Start & complete the Worldview intro 
- Select "More tours"
- Start & try to complete Brushfires in Australia --> Crashes at/around Step 4

**Review by Tomcariello — APPROVED** [review]

**Pull request merged**
