### PR TITLE
remove self value check against state value

### LINKED ISSUE #3341: Map won't drag after removing/re-adding layers in Compare mode
Testing [compare.swipe.1](https://wiki.earthdata.nasa.gov/display/WOR/S-26+%5Bcompare%5D%3A+Comparison)

After I remove the layers then re-add per instructions, I cannot drag the map and the compare line doesn't move the B side with it.

Mac, Chrome Version 88.0.4324.150
Screen Shot 2021-02-09 at 12 28 31 PM

### PR DESCRIPTION
**Pull request by edplato**
## Description

Fixes #3341  .

- [x] Remove self value check against state value for compare swipe position

## Further comments

If this is a relatively large or complex change, start a discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

## Checklist

This is simply a reminder of what we are going to look for before merging your code.

- I have read the [CONTRIBUTING](https://github.com/nasa-gibs/worldview/blob/master/.github/CONTRIBUTING.md) doc
- I have added necessary documentation (if applicable)
- I have added tests that prove my fix is effective or that my feature works (if applicable)
- Any dependent changes have been merged and published in downstream modules (if applicable)

@nasa-gibs/worldview

### CODE REVIEW

**Comment by jasontk19** [comment]
I'm gonna tag @Benjaki2 on this one as well since even though the `git blame` shows my name he was the original author of this change.  It was for something @minniewong wanted to do with compare mode on the HLS tour story branch I believe

**Comment by Benjaki2** [comment]
This code was added so that the `cv` value in the tour steps was used when present when clicking between tour steps. So we probably need a different fix.

**Comment by edplato** [comment]
I see what you're talking about with the tour step `cv`. I added back your `self.value` changes and made sure to update the `self.value` on a couple different cases. That seems to handle this issue and the tour step `cv` update problem.

**Review by jasontk19 — APPROVED** [review]
Nice, this fixes it!

**Pull request merged**
